### ISSUE TITLE
When using the perceval cache no connection should be created from the backend

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-perceval#109]
Ideally, when working with perceval caches, it should work offline.

**Comment by valeriocos** [comment]
This should have been achieved with the integration of the archive within the backends.
Should we close this issue?

**Comment by sduenas** [comment]
You're right but we can't close this issue yet. We still support cache. Once we remove it we'll close this issue.

**Comment by valeriocos** [comment]
Should we close this ticket @acs @sduenas ?

**Comment by acs** [comment]
Probably we need another ticket:

Ideally, when working with **perceval archive**, it should work offline. Right?

**Comment by valeriocos** [comment]
Yes sure, in the current implementation perceval requires internet connection only when fetching data from remote repositories.

**Comment by sduenas** [comment]
This was fixed when archive mode added. Closing it.
