### ISSUE TITLE
GitLab issues, wiki, CI support

### ISSUE THREAD

**Issue by ghost** [chaoss/grimoirelab-perceval#119]
_(Sorry if I missed this already planned somewhere.)_ I wonder if there's any possibility to add support for [GitLab](https://about.gitlab.com/) collaborative features (beyond just the git repos):

- CI / Runner
- Issues
- Merge requests
- Wiki

**Comment by sduenas** [comment]
It's in our plan but I can't estimate when it will be. The GitLab API is so similar to GitHub one, so it won't be difficult to have it soon but we need to improve the GitHub backend first.
In any case, we will keep you posted about this.

**Comment by jsmanrique** [comment]
Hi @downeym, I think @jgbarah has been working in something for it

**Comment by jgbarah** [comment]
Hi, @downeym 

For issues and (partially) merge requests, there is some support in https://github.com/jgbarah/perceval/tree/gitlab

It is almost functional, but I couldn't write the tests, and propose a pull request to upstream Perceval. Besides, maybe now would need some update.

I have it in my todo list, but not that high nowadays, sorry...

In any case, help is welcome ;-)

**Comment by valeriocos** [comment]
Hi @downeym 

https://github.com/grimoirelab/perceval/pull/252 provides supports for GitLab issues, notes and their emojis. This backend should be integrated soon to the codebase

**Comment by downeym** [comment]
Great news. Thanks for the update!

**Comment by vchrombie** [comment]
GitLab backend is integrated into GrimoireLab. The issues and merge requests can be analyzed using the data source.
The comments, reactions data of the issues, merge requests work is being integrated right now. https://github.com/chaoss/grimoirelab-elk/pull/881

Closing the issue as it is resolved. Please feel free to open new issue if needed.
