### ISSUE TITLE
Gitter import/index stats support

### ISSUE THREAD

**Issue by kapilt** [chaoss/grimoirelab-perceval#139]
we've got a few open source projects using bitter as their primary communication means with the community it would be nice to be able to bring stats on that into grimoire

**Comment by acs** [comment]
@kapilt could you provide the main URL for bitter project? Is it open source? Could you provide a list of open source projects using it? Thanks!

**Comment by sanacl** [comment]
@acs it seems to be Gitter

**Comment by kapilt** [comment]
re api https://developer.gitter.im/docs/welcome

**Comment by acs** [comment]
Hmmm, reading https://en.wikipedia.org/wiki/Gitter it seems the product will be «open source under an MIT License no later than June 2017» thanks to GitLab adquisition of it. @kapilt it is a pretty interesting project but right now we have no demand for it so there are not plans to implement a perceval backend in the short term.

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-perceval/pull/632
