### ISSUE TITLE
Error when running perceval with backend=jira on Windows

### ISSUE THREAD

**Issue by lluismf** [chaoss/grimoirelab-perceval#16]
It seems a problem with file separators, please see image for details:

![perceval](https://cloud.githubusercontent.com/assets/2213724/13333635/37ef443c-dc08-11e5-809a-8f43dce0b629.png)

**Comment by lluismf** [comment]
The same logic is present on all backend implementations btw.

**Comment by sduenas** [comment]
I don't have Windows so I can't test it but maybe you can try this on your machine.

You just need to replace the line 262 of `perceval/backends/jira.py` by the next two lines:

```python
base_path = os.path.join('~', '.perceval', 'cache')
base_path = os.path.expanduser(base_path)
```

Then, install and run Perceval again. If it works, I will change it on the rest of the backends.

**Comment by lluismf** [comment]
ok but I guess the URL will give problems too because the separator is / (Unix file separator). 
Also, it would be good to move this cache logic to the BaseCommand class. Does Python allow to call super methods in the initializer?

**Comment by shongoku** [comment]
Other backends occurs the same. I have a fork for windows. You can download in
github.com/shongoku/perceval
The correct branch is windows.

**Comment by sduenas** [comment]
Perceval doesn't support Windows. Users can try to use a vitual machine o the docker image of GrimoireLab to run this.
