### ISSUE TITLE
Support GitHub v4 API

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval#160]
There is a [new GitHub API](https://githubengineering.com/the-github-graphql-api/), based on GraphQL ([documentation](https://developer.github.com/v4/)). For some of the stuff Perceval does, it could be more appropriate than v3 (which is the one we're currentĺy using).

Besides, there is at least one Python package, [graphene](http://graphene-python.org/), which could help a lot with the implementation.

It would be nice if at least we explore to which extent this API could be useful.

**Comment by valeriocos** [comment]
Graphene seems to be used more on the server side (build/test APIs with GraphQL). Conversely, calls to GitHub v4 API are made using common HTTP requests which contain in their payload GraphQL code.

I've played a bit with the new API and pushed some examples at [github-v4-playground](https://github.com/valeriocos/perceval/blob/github-v4-explore/tests/test_github_v4.py)

As a first impression, the advantages to use the new API are:
- Live test of GraphQL queries (see [explorer](https://developer.github.com/v4/explorer/))
- Get nested data in one single query (ex.: get author and assignees for an issue)

The limitations are: 
- GraphQL requires to be explicit about the fields returned by a query (there is nothing similar to SELECT * in SQL), so in some cases we could have pretty long queries.
- It doesn't seem possible to retrieve nested paginated data in a single query. For instance, issues are generally paginated and some of them can have paginated comments. In this case, two queries should be written to deal with the pagination on issues and comments (as similarly done with REST API calls).

**Comment by acs** [comment]
Closing this ticket after the evaluation of GraphQL. We don't have plans to use it in the near future.
