### ISSUE TITLE
Optimize the number of calls to the GitHub API

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval#168]
Since comments and reactions were added to the backend, the number of requests made to the GitHub API has increased, making slower the fetching process. Moreover, the rate limit decreases faster.

To optimize the usage of the API, we can do something similar as in #163.

**Comment by valeriocos** [comment]
Should we close this issue?

**Comment by valeriocos** [comment]
This issue has been fixed by adding checks within the GitHub backend to avoid making requests to empty data (e.g., https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L266)
