### ISSUE TITLE
[git] Add Co-authored-by to the list of supported trailers

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-perceval#318]
GitHub shows commits co-authors if they are noted in the commit message using `Co-authored-by: ` trailer. Perceval might take that into account too.

More info: https://github.com/blog/2496-commit-together-with-co-authors

**Comment by acs** [comment]
Maybe we can use pair programming feature in gelk to analyze this new feature.

**Comment by Prabhat-IIT** [comment]
@jsmanrique I think you can close the issue now since it has been solved in [#289](https://github.com/chaoss/grimoirelab-elk/pull/289)
