### ISSUE TITLE
Add --to-date to plugins

### ISSUE THREAD

**Issue by pwnfoo** [chaoss/grimoirelab-perceval#324]
`--from-date` is a really awesome functionality but there is no option to mention an end date in any plugins.

It'd be awesome to have a `--to-date` or `--end-date` functionality to pull data within a given timeframe. This will he helpful for those who wants to pull data for just one year out of x years of data out of a given source.

**Comment by valeriocos** [comment]
Hi @sachinkamath, 
In the generic backend the option *--to-date* is [available](https://github.com/chaoss/grimoirelab-perceval/blob/9220d045a63a8d7a86056405a29005056785aa53/perceval/backend.py#L226
), however at the moment no specific backend supports it.

Indeed this could be a nice functionality to include in perceval, what do you think @sduenas?
