### ISSUE TITLE
Add support for Mattermost

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-perceval#325]
Since Perceval already supports tracking information from Slack, it might be interesting to support also Mattermost

Potential interesting info: [Mattermost API](https://api.mattermost.com/)

**Comment by sduenas** [comment]
I was having a look to Mattermost to know what kind of information we can get and how. Mattermost is a open source clone/rip of Slack platform that allows users to posts messages in one or several channels.

I think we should follow the same approach we did with Slack backend. The entry point will be a channel using its `channel_id` and Perceval with fetch the `posts` send to that channel. The id of a channel can be obtained in the dialog box that shows up after clicking in channel's `View Info` link. We'll use Personal  [Personal Access Token](https://docs.mattermost.com/developer/personal-access-tokens.html) as authentication method.

This is an example of how getting a set of posts, using pagination.

```
$ curl -H 'Authorization: Bearer heu9dw4q7bgjtxwnz9snp1ppor' "http://localhost:8065/api/v4/channels/cf6axeehstft9eq4nq5uk5jqby/posts?per_page=2&page=4"

{
    "order": [
        "1ju85sxo7bfab8nf3yk5snn17a"
    ],
    "posts": {
        "1ju85sxo7bfab8nf3yk5snn17a": {
            "id": "1ju85sxo7bfab8nf3yk5snn17a",
            "create_at": 1523525981213,
            "update_at": 1523525981213,
            "edit_at": 0,
            "delete_at": 0,
            "is_pinned": false,
            "user_id": "8tbwn7uikpdy3gpse6fgiie5co",
            "channel_id": "cf6axeehstft9eq4nq5uk5jqby",
            "root_id": "",
            "parent_id": "",
            "original_id": "",
            "message": "sduenas joined the team.",
            "type": "system_join_team",
            "props": {
                "username": "sduenas"
            },
            "hashtags": "",
            "pending_post_id": ""
        }
    }
}
```

The main issue is the posts are returned from newest to oldest which will make not possible to support resuming in case something fails while fetching those items.

User's information can obtained as in the next example:
```
$ curl -H 'Authorization: Bearer heu9dw4q7bgjtxwnz9snp1ppor' "http://localhost:8065/api/v4/users/8tbwn7uikpdy3gpse6fgiie5co"

{
    "id": "8tbwn7uikpdy3gpse6fgiie5co",
    "create_at": 1523525971112,
    "update_at": 1523525981147,
    "delete_at": 0,
    "username": "sduenas",
    "auth_data": "",
    "auth_service": "",
    "email": "sduenas@bitergia.com",
    "nickname": "",
    "first_name": "",
    "last_name": "",
    "position": "",
    "roles": "system_admin system_user",
    "locale": "en",
    "timezone": {
        "automaticTimezone": "",
        "manualTimezone": "",
        "useAutomaticTimezone": "true"
    }
}
```

Mattermost limits the access to its API using a rate limit. Same as Slack or GitHub.

**Comment by sduenas** [comment]
The latest version of `perceval` (see ab4f504) includes a new backend to fetch the messages sent to a Mattermost channel.
