### ISSUE TITLE
successfully installed perceval 0.9.10 on a Windows machine, but perceval  is not recognized as a command on the command prompt

### ISSUE THREAD

**Issue by kkc-al** [chaoss/grimoirelab-perceval#331]
when i try to run "perceval  --version" or "perceval --help" in the virtual environment, I get "'perceval' is not recognized as an internal or external command, operable program or batch file."

**Comment by kk-gndu** [comment]
even "Mordred --help" on the command prompt is not working. I am following  the tutorial 
Installing GrimoireLab Python modules available at https://grimoirelab.gitbooks.io/tutorial/content/before-you-start/installing-grimoirelab.html

**Comment by kk-gndu** [comment]
the list of modules installed in the virtual environment:
(grimoirelab) E:\venvs\grimoirelab\Scripts>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
beautifulsoup4 (4.6.0)
brewer2mpl (1.4.1)
certifi (2018.1.18)
chardet (3.0.4)
cheroot (5.8.3)
CherryPy (11.0.0)
click (6.7)
cycler (0.10.0)
Cython (0.27.3)
dulwich (0.18.6)
elasticsearch (6.1.1)
elasticsearch-dsl (6.1.0)
feedparser (5.2.1)
grimoire-elk (0.30.23)
grimoire-kidash (0.30.9)
grimoire-mordred (0.1.15)
grimoire-reports (0.1.5)
grimoirelab-panels (0.0.8)
grimoirelab-toolkit (0.1.4)
idna (2.6)
ipaddress (1.0.19)
Jinja2 (2.10)
kidash (0.4.2)
kingarthur (0.1.3)
MarkupSafe (1.0)
matplotlib (2.1.2)
numpy (1.14.0)
pandas (0.18.1)
perceval (0.9.10)
perceval-mozilla (0.1.5)
perceval-opnfv (0.1.4)
pip (9.0.1)
portend (2.2)
prettyplotlib (0.1.7)
PyMySQL (0.8.0)
pyparsing (2.2.0)
pypiwin32 (220)
python-dateutil (2.6.1)
pytz (2018.3)
PyYAML (3.12)
redis (2.10.6)
requests (2.18.4)
rq (0.10.0)
setuptools (38.5.1)
six (1.11.0)
sortinghat (0.5.2)
SQLAlchemy (1.2.2)
tempora (1.10)
urllib3 (1.22)
wheel (0.30.0)

**Comment by sduenas** [comment]
I can't check it because I don't have Windows installed. I'm not sure who pip installs packages on Windows systems. I think @valeriocos can check it.

**Comment by valeriocos** [comment]
The problem seems to be complicated to be solved quickly. We will investigate it.
In the meanwhile, you could use [Oracle VM VirtualBox](https://www.virtualbox.org/) to have Linux in your windows installation

**Comment by RobSmyth** [comment]
I'm having the same p[roblem. Has any work been done on this?

**Comment by MonikaEve** [comment]
Hi,
I have encountered the same problem and I've been trying to fix it for some time now. I also installed grimoirelab and perceval successfully inside a virtual environment. The problem is that there are only perceval and grimoirelab files of the type "File" in the \Scripts folder. I searched the virtual environment folder for a perceval file of the type 'application', but I couldn't find one. 
Here is the screenshot of the perceval file in the \Scripts folder
![percevalFile](https://user-images.githubusercontent.com/25267110/57136372-eaa51280-6dac-11e9-8935-e00a8775c5f1.png)
I couldn't upload the file itself, because the format wasn't supported. I turned it into a text document to upload it:
[perceval.txt](https://github.com/chaoss/grimoirelab-perceval/files/3141800/perceval.txt)

**Comment by valeriocos** [comment]
Hi @MonikaEve thank you for bringing this issue to life again.

Grimoirelab is developed on Linux and should work on any Linux-like platform. Currently, having Grimoirelab running on Windows is on the wishlist, but not at priority. However, if there is specific reason/advantage to use windows, please let us know and we can check all together how to move things forward. 

PS that file is python and it is basically the "application" file.

**Comment by valeriocos** [comment]
I executed perceval on my Windows machine using the following steps:
- Download python 3.6 from https://www.python.org/downloads/
- Create a shortcut of python.exe (e.g., `python36.lnk`) and move it to the Desktop. Python.exe is located where python has been installed, in my case is: `C:\Users\mylaptop\AppData\Local\Programs\Python\Python36`
- Install perceval from the terminal: `C:\Users\mylaptop\Desktop>pip3 install perceval`
- Execute Perceval from the terminal: `C:\Users\mylaptop\Desktop>python36.lnk C:\Users\mylaptop\AppData\Local\Programs\Python\Python36\Scripts\perceval github chaoss grimoirelab-toolkit`. 
  - `python36.lnk` is the python.exe
  - `C:\Users\...\Scripts\perceval` is the perceval "application" file 
  - `github chaoss grimoirelab-toolkit --category pull_request` is an example of perceval commands, in this case the github backend is executed to fetch pull requests data from https://github.com/chaoss/grimoirelab-toolkit

Hope this helps @MonikaEve @RobSmyth @kk-gndu
