### ISSUE TITLE
Check valid categories for backends

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#335]
The current signature of the fetch methods requires a category of the items to be collected. However, no check is done to ensure that the category passed in input is a valid/accepted one for the backend.

A solution could be to define a method which functionalities are similar to the following code:
https://github.com/chaoss/grimoirelab-perceval-mozilla/blob/master/perceval/backends/mozilla/remo.py#L93

**Comment by sduenas** [comment]
That's a great idea. I think the backend should have a property, probably called `categories` that would return a list of the supported categories (most of the times it will be only one). Therefore, `fetch` method on `Backend` class can get the categories en check whether the given one is valid or not.

I suggest to check it inside backends parent class to avoid code duplication.

**Comment by valeriocos** [comment]
Cool! yes, the idea is to delegate this check to the parent backend.
I'll start working on this asap
