### ISSUE TITLE
SQLite error related to threads

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval#337]
I'm testing the current version of Perceval (master HEAD) with a current version of the whole stack, from mordred. When running it, I see:

```
Exception ignored in: <bound method Archive.__del__ of <perceval.archive.Archive object at 0x7f1d7a174908>>
Traceback (most recent call last):
  File "/tmp/gl/lib/python3.5/site-packages/perceval/archive.py", line 104, in __del__
    conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139764611151616 and this is thread id 139764693935872
```

I'm not sure if this is enough info to debug this, or even if it is really a Perceval issue, but since this is new with this version, and refers the archive, I thought maybe it is. Let me know if you need some more details.

**Comment by jgbarah** [comment]
More info: after some tests, this seems to happen only sometimes. I couldn´ t find a pattern yet :-(

**Comment by sduenas** [comment]
This isn't a Perceval issue. There's only one place were threads are in use: git backend. This backend don't support nor uses the archive, though.
