### ISSUE TITLE
Duplicated commit update problem

### ISSUE THREAD

**Issue by pine0207** [chaoss/grimoirelab-perceval#359]
Hello,
I found several issues on backend.
You know,
1. (git) fetch latest commit infinitely. (latest 1 commit repeat)
2. (jira) often reset from_date. (initial: 1970-01-01)

These problems are update issue on backend.
I guess Perceval's Scheduler has a wrong logic like a timestamp.

Plz, check these problems.
Thanks.

**Comment by valeriocos** [comment]
Hi @pine0207, thank you for reporting this problem.
Perceval doesn't embed any scheduler, that task is handled by mordred.

Do you have some examples to test this wrong behaviour. 
Which versions of perceval, mordred and elk are you using?

**Comment by pine0207** [comment]
Thanks to your answer @valeriocos .

Perceval's Scheduler means that Arthur's one. Sorry to misunderstand.
But, I think it isn't Arthur's problem. It relate on Perceval and backend.

I use 0.9.10 perceval version, and all grimoire lab component using. (mordred, elk, even arthur)
As you know, it is old version, but the thing is duplicated fetching.

Below is example I tested.
1. Launch Arthurd.
2. Launch a Arthurw.
3. Launch Mordred.
4. Arthur assigned create job to Perceval : Running job #arthur-ssh://.... (git)
5. Perceval running command git fetch ssh://.... (git)
6. In git repository, there are 10 commits.
   At first, 10 commits fetched all. Because it is a first step.
7. **Problem cause.**
   Arthur assigned update job to Perceval : Running job #arthur-ssh://.... (git)
   Perceval running command git fetch ssh://.... (git)
   Already, fetched all 10 commits. There are any new commit in git repository.
   However, Perceval fetch 1 latest commit, infinitely.
   **_perceval.backends.core.git - INFO] - Fetch process completed: 1 commits fetched_**

In case of JIRA, step 7 often reset from_date initial value 1970-01-01.
It is a sample scenario about error case.

**Comment by pine0207** [comment]
I found that reason.
_**git log --since [from_date]**_ 
'since' option means contain 'from_date' commit.

But, I want to fetch newest commit.
Plz check me out.
Thanks.

**Comment by valeriocos** [comment]
Hi @pine0207 , sorry for the late reply.
If you use the parameter latest-items, you should be able to fetch only the latest commits. Thus, the first iteration will collect all commits available, while the other iterations will fetch 0 commits (until no new commits are available).
In your json describing the task, add this:
```
{
    "tasks": [
        {
            ...
            "backend": "git",
            "backend_args": {
                ....
                "latest_items": "true"
            },
	    ...
        }
    ]
}
```

**Comment by valeriocos** [comment]
I'll check the issue with Jira and reply at https://github.com/chaoss/grimoirelab-kingarthur/issues/27

**Comment by sduenas** [comment]
I'm closing this ticket because it isn't related to `perceval`.

As @valeriocos said, you have to use `--latest-items` in `arthur` to don't get duplicated commits. `athur`. `arthur` sets, in recurring jobs, the last date obtained in the previous one as the date to start getting new items. It's the only way to ensure you're not missing anything new that was created at the same time, but for any reason, it didn't get it the first time.
