### ISSUE TITLE
[gerrit] url should be hostname

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval#368]
Currently, the help for `perceval gerrit` reads:

```
usage: perceval [-h] [--category CATEGORY] [--tag TAG] [--from-date FROM_DATE]
                ...
                url
```

However, the "url" is not really an url, but the host name where ssh access to the Gerrit instance is granted. I would change this to "hostname".

If this change is done, very likely variable names and paramerters in the Python interface should also be changed from "url" to "hostname".

Do others agree with this change?

**Comment by sduenas** [comment]
That makes sense.
