### ISSUE TITLE
Git backend [Windows 7/10] issue

### ISSUE THREAD

**Issue by muhmaz3** [chaoss/grimoirelab-perceval#399]
For us GitHub backend  works, but the Git backend is not working.  Git is already Install on our test machine, we can clone the repo by using Git command line. We used Perceval example code, but we got an error.  Looking into the  git backend, **if we set `evn = None`, line 1268 then it works.** But  we could  not figure out which environment variable we are missing or why it works  when `env= None`. Any guidance on this will be really helpful. 

`repo_url = 'https://github.com/chaoss/grimoirelab-perceval'`
`repo_dir = 'chaooos2'`
`repo = Git(uri=repo_url, gitpath=repo_dir)`

`# fetch all commits as an iteratoir, and iterate it printing each`
`for commit in repo.fetch():`
   `print(commit['data']['commit'])`

> **git command - fatal: unable to access  'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com**

**Comment by sduenas** [comment]
Sorry for the late response. I'm not sure about how environment variables work in Windows but `HOME` variable is needed because it's where git configuration file is stored. I'm afraid `os.getenv('HOME', '')` doesn't find this variable and sets its value to `''` which would make your code fail. I'm not sure about this, though.

Would you try to run just this snippet so we can figure out whether `HOME` exists or not?

```
import os
env = os.getenv('HOME', '')
print("HOME:", env)
```

More info about Git environment variables can be found in [Git Internals Environment Variables](https://git-scm.com/book/gr/v2/Git-Internals-Environment-Variables) and [Getting Started with Git Setup](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)

**Comment by jgbarah** [comment]
Maybe there is no HOME in Windows: http://www.itprotoday.com/management-mobility/what-environment-variables-are-available-windows

What do you think about checking for HOME, and if that fails, check for HOMEPATH? (or check for Windows, and have a different code in that case, directly reading HOMEPATH....)

**Comment by muhmaz3** [comment]
@sduenas I have tried your suggestion and as @jgbarah mentioned, there is no HOME on windows and I also got returned default value. Thereafter, I tried  HOMEDRIVE, and HOMEPATH, USERPROFILE, non of them worked.

**Comment by jgbarah** [comment]
Weird that HOMEDRIVE and HOMEPATH didn't work... I assume that you checked them using the snippet @sduenas proposed, switching HOME for HOMEDRIVE and HOMEPATH, and you saw the output was the empty string, right?

Could you please check which variables you have defined in your environment? You could run this script:

```
import os
print(os.environ)
```

as (assuming the file with the script is `test.py`):

```
python3 test.py
```

**Comment by jgbarah** [comment]
Weird that HOMEDRIVE and HOMEPATH didn't work... I assume that you checked them using the snippet @sduenas proposed, switching HOME for HOMEDRIVE and HOMEPATH, and you saw the output was the empty string, right?

Could you please check which variables you have defined in your environment? You could run this script:

```
import os
print(os.environ)
```

as (assuming the file with the script is `test.py`):

```
python3 test.py
```

**Comment by jgbarah** [comment]
OK, I see. Then, if all of these are correctly set, maybe it would be a matter of either:

* Checking if running on Windows, and in that case use those instead of HOME or,
* Checking if HOME is defined, if not, check those, hoping that we're running on Windows.

@sduenas what do you think?

**Comment by sduenas** [comment]
@muhmaz3 would you try with this?

```
    env = {
        'LANG': 'C',
        'HOME': os.getenv('USERPROFILE', '')
    }
```

You have to change it on line **805** of **perceval/backends/core/git.py**. Please run perceval with the debug flag active: `perceval -d`. Please paste her the output.

**Comment by muhmaz3** [comment]
@sduenas 
After changing on line 805 as mentioned, I got the following
```
Scripts>python ./perceval -d
usage: perceval [-c <file>] [-g] <backend> [<args>] | --help | --version
perceval: error: the following arguments are required: backend, backend_args
```

**Comment by muhmaz3** [comment]
```
\Scripts>python ./perceval -d git https://github.com/chaoss/grimoirelab-perceval --git-path C:\abc
usage: perceval [-c <file>] [-g] <backend> [<args>] | --help | --version
perceval: error: unrecognized arguments: -d
```
The error which I get without using the option -d
```
\Scripts>python ./perceval -g git https://github.com/chaoss/grimoirelab-perceval --git-path C:\abc
[2018-07-24 12:00:20,310 - root - INFO] - Sir Perceval is on his quest.
[2018-07-24 12:00:20,315 - perceval.backends.core.git - INFO] - Fetching commits: 'https://github.com/chaoss/grimoirelab-perceval' git repository from 1970-01-01 00:00:00+00:00 to 2100-01-01 00:00:00+00:00; all branches
Traceback (most recent call last):
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 382, in run
    for item in items:
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 492, in fetch
    raise e
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 486, in fetch
    for item in items:
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 149, in fetch_items
    latest_items)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 265, in __fetch_from_repo
    commits = self.__fetch_commits_from_repo(repo, from_date, to_date, branches)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 294, in __fetch_commits_from_repo
    repo.update()
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 900, in update
    self._exec(cmd_update, cwd=self.dirpath, env=self.gitenv)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 1282, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./perceval", line 194, in <module>
    main()
  File "./perceval", line 112, in main
    cmd.run()
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 389, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com
```

**Comment by sduenas** [comment]
I think `C:\abc` (the place where you are storing the repository is not empty. Will you run it again using an empty directory?

**Comment by muhmaz3** [comment]
No, I have tried that long ago, and I have also tried it again as well just now, I get the same error. 

My make shift solution in which I set `env = None` (mentioned in my first post) works. I have also tested it on two different window machines.  As you have mentioned and I agree I got to do something with environment variable. 

I can do one more test, If you kindly tell me which git configuration file it needs, then I can create an environment variable to that file and see if it works ?

**Comment by sduenas** [comment]
According to the traceback, perceval is running an update over that directory instead of a clone. That means the repository already exists there. In any case, have you changed the `HOME` env variable in all its occurrences in the code (`'HOME': os.getenv('USERPROFILE', '')`). In this case, on line **786**. As I supposed you where running it on an empty repository, I only asked you to change the code for the `clone` command and not for the rest.

**Comment by muhmaz3** [comment]
I got your point, I have tried with empty directory, same error, I have also changed line 786 as per your suggestion.  
```
\Scripts>python ./perceval git https://github.com/chaoss/grimoirelab-perceval --git-path C:\aff
[2018-07-24 13:55:42,950] - Sir Perceval is on his quest.
https://github.com/chaoss/grimoirelab-perceval
Traceback (most recent call last):
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 382, in run
    for item in items:
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 492, in fetch
    raise e
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 486, in fetch
    for item in items:
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 149, in fetch_items
    latest_items)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 262, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 312, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 817, in clone
    cls._exec(cmd, env=env)
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backends\core\git.py", line 1282, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository 'C:\aff'...
fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./perceval", line 194, in <module>
    main()
  File "./perceval", line 112, in main
    cmd.run()
  File "C:\Users\muhammad\Anaconda3\lib\site-packages\perceval\backend.py", line 389, in run
    raise RuntimeError(str(e))
RuntimeError: git command - Cloning into bare repository 'C:\aff'...
fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com
```

**Comment by sduenas** [comment]
I'm wondering whether this issue is related to this (https://stackoverflow.com/questions/20370294/could-not-resolve-host-github-com-error-while-cloning-remote-repository-in-git). We should be missing an environment variable required in Windows to make this work.

**Comment by MehdiGol** [comment]
I have the same problem... I also set the proxy and unset it. no change. please help me...

**Comment by sduenas** [comment]
As far as I know, none of the developers have a Windows system running, so it's not possible for us to test it. It should be something related to the environment variables. Try to modify them into https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L783 and in https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L805

Try if removing the usage of the `env` dict, it will clone the repository at least. You can do it in the next line. Just write:
```
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
```

https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L1265
