### ISSUE TITLE
Config option in perceval: should we remove it ?

### ISSUE THREAD

**Issue by MalloZup** [chaoss/grimoirelab-perceval#428]
After i did some research on the configuration option `-c` for perceval to me look like that this functionality is not working well + undocumented.
( see pr on wip: https://github.com/chaoss/grimoirelab-perceval/pull/427)

What is not working a part of documentation:

if you see here `defaults` var https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L99
this var is not used for the backend meta-class.. i don"t see any method that take advantage of that data ( i tried it out with this  cfg file:)

``` 
[github]
owner = "chaoss"
repository = "grimoirelab-perceval"
```
and calling
```
perceval -c perceval.cfg 
```
but perceval was complaining  that repository was missing

Ok we can implement/fix that feature but..  : 

To me since we have https://github.com/chaoss/grimoirelab-kingarthur which is the scheduler working with files for scheduling various instances of perceval, i don"t see this option `-c` as really needed.

Additionally it seems to me to be a ghost feature which we can safely remove.
https://github.com/chaoss/grimoirelab-perceval/commit/589bc515db1632959f6edcb0c4bc2fe43ee51b74
(just looking the initial implementation was more kind of debugging/printing args)

Personally i would vote to remove this config parameter for perceval since for that there is king-arthur ( and we spare an additional option that can led to complexity), but i just opened the issues to discuss it with you

**Comment by valeriocos** [comment]
Hi @MalloZup thank you for the PR #427 and for raising an interesting point. I checked the code and the option `-c` of Perceval doesn't seem to work.

I agree with you about deleting this feature.

In case you want to dive into a possible fix, the logic to implement should not be so different from the one in the method [_compose_perceval_params](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task.py#L116). In a nutshell, the backend parameters are parsed and converted to a list, which is finally passed to `BackendCommand` of a given Perceval backend (e.g., https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L715)

@sduenas , what you think about deleting the `-c` param of Perceval?

**Comment by MalloZup** [comment]
@sduenas @valeriocos thanks for your reply i will take care of the removal here :slot_machine: :jack_o_lantern: :japan: :wink:

**Comment by MalloZup** [comment]
merged
