### ISSUE TITLE
Windows - problems cloning a github repo

### ISSUE THREAD

**Issue by gaurav5430** [chaoss/grimoirelab-perceval#447]
On windows 8, this is how i made perceval work within a Windows installation:

**Installing perceval**
while trying to install with pip i got into problems with dulwich on windows trying to build the optional C extensions which probably requires a C compiler on path , so did a separate install of dulwich with --global-option="--pure" . This required installing dulwich dependencies, and then i had to install perceval with --global-option="--pure" .

```
pip3 install certifi urllib3
pip3 install "dulwich==0.18.6" --global-option="--pure"
pip3 install perceval
```
Finally got it to work within a virtual environment (named 'gl') like this:

`cmd > gl\Scripts\python gl\Scripts\perceval git https://github.com/chaoss/grimoirelab-perceval.git `, but then it tries to clone this repo to a local path which has the full repo url in the name, and so windows refuses to create it and throws an error like : `git command - fatal: could not create leading directories of 'C:\Users\...\https://github.com/chaoss/grimoirelab-perceval.git-git` . This does not work because the name that perceval uses for the cloned repo is not in a correct format. To get over it, I tried to use the --git-path flag, which leads to another issue:  Couldn't resolve host 'github.com' . I think it might be similar to https://github.com/chaoss/grimoirelab-perceval/issues/399

Please note that i was able to make it work with local git repo and see the commits.

**Comment by sduenas** [comment]
We don't support Windows. I'm closing this ticket.
