### ISSUE TITLE
Problem while fetching issues via GitHub() 

### ISSUE THREAD

**Issue by musman-ashraf** [chaoss/grimoirelab-perceval#457]
While fetching issues from a repo, half way through I am getting the following. 

raise RateLimitError(cause=cause, seconds_to_reset=seconds_to_reset)RateLimitError: Rate limit exhausted.; 3058.0 seconds to rate reset.

any fix I need to do in code in order to avoid it and fetching all the issues via Github().

**Comment by valeriocos** [comment]
Hi @musman-ashraf , have you tried to set the param [sleep-for-rate](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L77) to True?

**Comment by musman-ashraf** [comment]
where should I set it?

**Comment by valeriocos** [comment]
If you are executing perceval from Python, you should have something like:
```
github = GitHub("chaoss", "grimoirelab-perceval", "your-token", sleep_for_rate=True)
issues = [issues for issues in github.fetch()]
```

If you are using perceval from commandline, you should have something like:
```
perceval github chaoss grimoirelab-perceval -t your-token --sleep-for-rate
```

**Comment by valeriocos** [comment]
@musman-ashraf I'm going to close this issue. Feel free to reopen it if you need.

**Comment by musman-ashraf** [comment]
It worked fine. Thank you for your time.
