### ISSUE TITLE
Fetching followup commits of pull requests

### ISSUE THREAD

**Issue by musman-ashraf** [chaoss/grimoirelab-perceval#460]
Hi, I want to fetch commits related to pull request. So far, Github.fetch() returns me pull requests without having commits details.

However trying Github.fetchitems thorws the follwing ...
github.py", line 241, in __fetch_pull_requests
    raw_pulls = self.client.pulls(from_date=from_date)

AttributeError: 'NoneType' object has no attribute 'pulls'

**Comment by valeriocos** [comment]
Hi @musman-ashraf 

Please, try the code below and let me know. It retrieves the pull requests of chaoss/grimoirelab-perceval and insert the pull request number and the corresponding commits to a dict.
```
from perceval.backends.core.github import (GitHub, CATEGORY_PULL_REQUEST)
        
github = GitHub("chaoss", "grimoirelab-perceval", "your-token")
pr2commits = {}

for pull in github.fetch(category=CATEGORY_PULL_REQUEST):
    data = pull['data']
    pr2commits.update({data['number']: data['commits_data']})

return pr2commits
```

**Comment by valeriocos** [comment]
@musman-ashraf let's close this issue, feel free to reopen it if needed
