### ISSUE TITLE
How to get GitHub username from Git history?

### ISSUE THREAD

**Issue by sulunemre** [chaoss/grimoirelab-perceval#462]
When a git repository is hosted on GitHub, can I get GitHub username for a commit with the help of perceval? GitHub API provides that information([for example](https://api.github.com/repos/chaoss/grimoirelab-perceval/commits/89fc35bd518468f7bbf6daab5da35985d872f0ed)) but is it available on perceval?

**Comment by sduenas** [comment]
Although GitHub API provides that, Perceval currently doesn't support it. Perceval only gathers data from issues and PRs (what we call `categories`). Any PR will be welcome to support `commit` category.

**Comment by valeriocos** [comment]
Hi @sulunemre, 
The feature you mention is not covered by Perceval, but implemented in [ELK](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L237), another component of GrimoireLab. In case you were planning to use the data extracted with the Git backend, you may do the following:
- execute the Git backend on a GitHub repository
- collect the JSON documents
- iterate over the JSON documents and use the commit hashes to send requests to the GitHub API as done [here](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L245)

If you need support to write the script, let me know, I'll help you :)

**Comment by valeriocos** [comment]
@sulunemre I would close this issue, feel free to reopen it if needed.
