### ISSUE TITLE
Add category to fetch GitHub repositories metadata

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval#480]
The entry point for repositories in GitHub REST API provides basic information such as number of stars, forks and watchers: https://developer.github.com/v3/repos/

A new category should be added to GitHub backend to retrieve this kind of data.

This issue is related to chaoss/grimoirelab#184.

**Comment by valeriocos** [comment]
The PR https://github.com/chaoss/grimoirelab-perceval/pull/481 addresses this issue.
