### ISSUE TITLE
What's the best way to incrementally update your data?

### ISSUE THREAD

**Issue by choldgraf** [chaoss/grimoirelab-perceval#482]
Hello 👋 I think perceval looks really cool! I'm exploring using it to keep a running dataset of several of our repositories, and mining that data to find ways we can improve our community dynamics!

I'm still trying to figure out the right way to store data...right now I'm just storing things as JSON lines. But this brings up the challenge of *updating* data once an initial data-dump has been accomplished. How do folks recommend doing this? I could do something like:

* Read the current jsonlines file
* Find the latest date
* Set that as the `from_date` argument
* Output to a temporary JSON lines file
* Use something like Pandas to concatenate the two and write back to the original file

But that seems a little bit hacky, and I wonder if there's a built-in way to handle this. It would certainly make my life easier, since the GitHub fetcher makes a large number of API requests and I hit my limit almost immediately!

Thanks for the help!

**Comment by valeriocos** [comment]
Hi @choldgraf , thank you for using Perceval. Arthur seems the tool you may need (https://github.com/chaoss/grimoirelab-kingarthur), in a nutshell it's a scheduler of Perceval jobs (and it takes care of incrementality). You may want to have a look also to mordred (https://github.com/chaoss/grimoirelab-sirmordred), which is the orchestrator of GrimoireLab, and it provides support for incrementality, storage (perceval data is stored in ElasticSearch indexes) and other things. Don't hesitate to write if you need further help.

**Comment by choldgraf** [comment]
Hey @valeriocos - thanks for the ideas :-)  I had originally looked into kingarthur and sirmordred, but I feel like these are a bit heavy-handed for me. I had checked out the kingarthur docs, but in the getting started page it says 

"The first step is to run a Redis server that will be used for communicating Arthur's components. Moreover, an Elastic Search server can be used to store the items generated by jobs."

and I don't know what either redis servers of elastic search servers are :-) so I concluded that this would be too much overhead for me. This is more of a side-side interest of mine...I'm working on an open project so we don't really have $$$ to pay engineers to figure out this kinda stuff :-/ 

I can try digging through the docs over the coming weeks if kingarther/sirmordred are the right way to do this!

**Comment by valeriocos** [comment]
@choldgraf no worries. If you pass me a list of repositories you want to analyze, I can setup things for you and share with you the configuration (no $$$ needed).
Note that Grimoirelab components are available also on Docker, so you may not need to dig into the specificities of the technologies used.

**Comment by valeriocos** [comment]
@choldgraf I'm going to close this issue, feel free to reopen it if needed.

**Comment by choldgraf** [comment]
no problem, and thanks for the help (and your offer to help). I'll dig into the Docker image when I have a moment and can try to figure that one out :-)
