### ISSUE TITLE
[github] perceval commandline auth by user and password

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-perceval#483]
I had a look at other issues and pull requests but have n't found one addressing this issue. The [grimoirelab tutorial documentation](https://chaoss.github.io/grimoirelab-tutorial/perceval/github.html#retrieving-from-github-with-authentication) states:

> In that help banner, we see three different ways of using it:
   with no credentials
   with a user and password
   with a user token

> To avoid the problems with the unauthenticated access to the GitHub API, we can use the Perceval GitHub backend with authentication:
```
(perceval) $ perceval github grimoirelab perceval --sleep-for-rate \
    -u jgbarah -p XXX
```

I'm using v0.12.3 and the `-u` and `-p` flags are not available. I checked with the `perceval github --help` command. When I went through the perceval github backend, I was unable to locate said arguments. 

Is it just a an inconsistency in the documentation? Should I open an issue in the grimoirelab-tutorial repo to update the documentation?

Or is it something else?

**Comment by valeriocos** [comment]
Hi @Polaris000 , sorry for the late reply. It seems that it is just an inconsistency in the documentation. the GitHub perceval backend can use an API token, but doesn't support the use of username and password.
It would be amazing if you could open an inssue in the grimoirelab-tutorial [repo](https://github.com/chaoss/grimoirelab-tutorial) to update the documentation (thank you a lot).

I would close this issue if you agree.

**Comment by Polaris000** [comment]
Thanks for the reply! I'll send a PR in the grimoirelab tutorial repo.
