### ISSUE TITLE
[doc] Update info about categories returned by Perceval

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#494]
The information about the categories returned by Perceval is not updated with the latest codebase:
- https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L35
- https://github.com/chaoss/grimoirelab-perceval#usage

Furthermore, wrt the GitHub categories, some more information could be added at the lines below to explain the overlap of some of the data returned when fetching issues and pull requests.
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L571
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L586

**Comment by jgbarah** [comment]
Thanks to chaoss/grimoirelab-tutorial#74 this is now fixed in the tutorial. But README and help for Perceval itself, explaining categories for GitHub, are not done. PRs welcome.

**Comment by vchrombie** [comment]
> Thanks to [chaoss/grimoirelab-tutorial#74](https://github.com/chaoss/grimoirelab-tutorial/pull/74) this is now fixed in the tutorial. But README and help for Perceval itself, explaining categories for GitHub, are not done. PRs welcome.

I would be happy to contribute.
Can I take up this issue and send a patch for it?

**Comment by valeriocos** [comment]
Thank you @vchrombie , sure! You can start with:

> The information about the categories returned by Perceval is not updated with the latest codebase:
> 
> https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L35
> https://github.com/chaoss/grimoirelab-perceval#usage

**Comment by vchrombie** [comment]
I updated it in the README. Should I update that in the codebase too?

What I am thinking is, updating about the `category` here looks cluttered.
https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L35ter

Or shall I add it as a `optional argument for github` under this line in the codebase?
https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L75

**Comment by valeriocos** [comment]
Yes, sure. I would modify here: https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L50, something like:
`github           Fetch issues, pull requests and repository information from GitHub`

Also GitLab could be changed since it includes [two categories ](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gitlab.py#L87)

what do you think ?

**Comment by valeriocos** [comment]
If you want, you can improve also the method descriptions in github.py. As a reference, you can take a look at the methods in [git.py](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L910)

**Comment by vchrombie** [comment]
Sure @valeriocos, I will update you with the changes.

**Comment by valeriocos** [comment]
Great, thank you @vchrombie
