### ISSUE TITLE
[feature-request] Progress bar showing the stats of retrieving data using Perceval.

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-perceval#499]
I was using Perceval to get the data of GitHub projects and I observed one thing that the user doesn't know how much of the scraping is done or how much is still pending.

How about adding a progress bar which can show the statistics of the data retrieval work like when you update your packages in Ubuntu, you get the progress bar like the last line in the below picture.

![Screenshot_20190329_031637](https://user-images.githubusercontent.com/25265451/55195054-5ce46f00-51d1-11e9-8461-a206f6338a47.png)

If we can get the number of items we are gonna scrape, then I think this can be implemented.

_Example:_ If we are getting the data of issues of a particular project, we can get the count in the starting of the program and have a current scraping counter which can be used to update the percentage of work completed.

I am not sure whether this is gonna be a good idea but it would be good to have it so that people can have a track of the work. I am not sure about its implementation in other backends like bugzilla and discourse. Need to have a look if we can get the total number in the starting.

I would be happy to work on this if you feel it as a good and valid feature. :slightly_smiling_face:

**Comment by valeriocos** [comment]
Hi @vchrombie , thank you for sharing this idea. It could be a nice feature, but it won't work for all backends. For instance, AFAIK the GitHub API doesn't return the number of all issues (just the number of [open ones](https://developer.github.com/v3/repos/)), you can get that number by scrolling the paginated issues. Maybe, the GitHub GraphQL API offers this kind of feature, but IMHO I would avoid mixing different APIs.

Other backends could work, for instance [stackexchange](https://github.com/chaoss/grimoirelab-perceval/blob/c80f6696bfca44cd77971abde339fd51e7633a7c/perceval/backends/core/stackexchange.py#L227)

**Comment by valeriocos** [comment]
if you agree @sduenas , we can close this issue. Although the idea is interesting, it doesn't seem to be feasible. Thank you @vchrombie for the proposal.

**Comment by vchrombie** [comment]
> It could be a nice feature, but it won't work for all backends. 

I was also thinking about it.

> IMHO I would avoid mixing different APIs.

Ya, true that. One of the rules of a good software product; Keep It Simple. :)

**Comment by vchrombie** [comment]
> if you agree @sduenas , we can close this issue. Although the idea is interesting, it doesn't seem to be feasible. Thank you @vchrombie for the proposal.

You're welcome. I am okay with it. We can close this issue. :+1:

**Comment by vchrombie** [comment]
> if you agree @sduenas , we can close this issue. Although the idea is interesting, it doesn't seem to be feasible. Thank you @vchrombie for the proposal.

You're welcome. I am okay with it. We can close this issue. :+1:
