### ISSUE TITLE
Extra commits fetched by perceval

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-perceval#500]
When perceval is run on certain repositories, the number of commits fetched by perceval is different from the number visible on the repository's page on github. 

Though I looked around, and even fetched data from a different set of repositories, the number of commits fetched is still different in some cases. 

Since the data is thousands of lines long, it is not easy to tell which commits are extra. Though there could be a problem in the script I have written, the number of pull requests and issues tallies. 

Which commits are excluded when displaying the count on github?
@valeriocos 
Let me know if you require the script.

**Comment by valeriocos** [comment]
Thank you @Polaris000 for reporting this issue. Under the hood, once Perceval has cloned a repository, it executes the command below, which retrieves the commits in all refs. This should explain the mismatch you see.
```
git log --raw --numstat --pretty=fuller --decorate=full
                --all --reverse --topo-order --parents -M -C -c
                --remotes=origin
```

Feel free to have a look at the documentation of the method and the Git log command (to know each param what it does):
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L982
- https://git-scm.com/docs/git-log

> Which commits are excluded when displaying the count on github?

GitHub shows just the commits per branch (or tag), it doesn't give you the total number. For performance purposes, Perceval retrieves all commits at once.
If everything is ok, the set commits you retrieve for a branch should be always a subset of what is returned by Perceval. A special case is when the Git backend is executed with the flag `--latest-items`, in this case, if a repository has been already cloned locally, Perceval returns only the new commits after the last fetch operation.

**Comment by Polaris000** [comment]
Thanks for the prompt reply @valeriocos! I'll have a look at the resources you mentioned. I'll close this issue once I've had a look.

**Comment by Polaris000** [comment]
I can't believe I forgot that github by default shows you the main development branch (generally master)! Thanks a lot for your time!
The thing that threw me off was that my script for getting master commits was slightly incorrect. 

Once again, thanks!

**Comment by valeriocos** [comment]
You're welcome @Polaris000 :)
