### ISSUE TITLE
Specifying the --from-date and --to-date formats in the help messages for the backends.

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-perceval#503]
Hey @valeriocos @jgbarah, I tried running perceval with different date formats for the --from-date, --to-date fields, and it supports many formats. But just to avoid the dilemma for the user regarding the input date format, would it be nice if it is explicitly stated in the help message (for eg, it could be YYYY-MM-DD or DD-MM-YYYY). Please let me know about this or I shall close it :sweat_smile:

**Comment by jgbarah** [comment]
I think it could be a good idea to have a valid format in the help message, yes... What do you think, @valcos, @sduenas?

**Comment by valeriocos** [comment]
+1

Thank you @harshalmittal4 for the proposal. The formats supported are the following ones: https://github.com/chaoss/grimoirelab-toolkit/blob/master/grimoirelab_toolkit/datetime.py#L97. I guess the description of supported formats (or a subset) could go over here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L311

What do you think @sduenas ?

**Comment by harshalmittal4** [comment]
> This functions supports several date formats like YYYY-MM-DD,
    MM-DD-YYYY, YY-MM-DD, YYYY-MM-DD HH:mm:SS +HH:MM, among others.
    When the timezone is not provided, UTC+0 will be set as default
    (using `dateutil.tz.tzutc` object).

@sduenas Please have a look.
Thanks @jgbarah, @valeriocos. Let me know what formats to be added if this is to be included.

My views on this : We must add atmost 2 supporting formats, so that the help message appears prompt.

**Comment by harshalmittal4** [comment]
Hey @jgbarah, @valeriocos, @sduenas, ping.
Please let me know which formats to show in help message, for now shall I go with these two:
`YYYY-MM-DD and MM-DD-YYYY`

**Comment by valeriocos** [comment]
@harshalmittal4 thank you for the ping.
What do you think about changing the help message at:
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L317
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L320

with something like:
```
help="fetch items updated since this date (e.g., YYYY-MM-DD, MM-DD-YYYY)"
help="fetch items updated before this date (e.g., YYYY-MM-DD, MM-DD-YYYY)"
```

what do you think ?

**Comment by harshalmittal4** [comment]
Yes @valeriocos, they seem good.  We could also replace the word `e.g.` with `format`.
Anyways, so shall I modify it according to this : 
`help="fetch items updated since this date (e.g., YYYY-MM-DD, MM-DD-YYYY)"
help="fetch items updated before this date (e.g., YYYY-MM-DD, MM-DD-YYYY)"`

**Comment by harshalmittal4** [comment]
@valeriocos @jgbarah ping! :sweat_smile::

**Comment by valeriocos** [comment]
I would prefer to use `e.g.,` instead of `format` since the former provides some valid examples, while the latter seems to me that the  YYYY-MM-DD, MM-DD-YYYY are the only valid formats.

Please @harshalmittal4 submit the PR when you have time, thank you.

**Comment by harshalmittal4** [comment]
>I would prefer to use e.g., instead of format since the former provides some valid examples, while the latter seems to me that the YYYY-MM-DD, MM-DD-YYYY are the only valid formats.

Yes, @valeriocos, agreed. `format` seems to put stricter restrictions, I get it :thinking: 
I have made the PR accordingly, please review.
Thanks!
