### ISSUE TITLE
Error in retrieving pull_request data for a particular repository

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-perceval#507]
I am trying running perceval for retrieving pull_requests data for [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI) repository using the command
`perceval github -t XXXX --json-line --sleep-for-rate --category pull_request Cloud-CV EvalAI >> evalai_info.json`
but getting the following error message after retrieving some data : 
![Screenshot from 2019-04-02 11-52-42](https://user-images.githubusercontent.com/24206326/55380487-f7301400-553d-11e9-9f72-652ac97be26b.png)

What is unusual is this is happening only for **this repository**, and only for the **pull_request category**.
What could possibly be the issue with this.

**Comment by harshalmittal4** [comment]
The error message seems to suggest that `self.__get_user(comment['user']['login'])
` is returning NoneType object.

**Comment by valeriocos** [comment]
Thank you @harshalmittal4 for reporting this issue. I'm checking it

**Comment by valeriocos** [comment]
This issue has been already reported for another repo: https://github.com/chaoss/grimoirelab-perceval/issues/459

**Comment by harshalmittal4** [comment]
Hey @valeriocos, I went through the issue #459. May I send a PR for this according to @sduenas comment [here](https://github.com/chaoss/grimoirelab-perceval/issues/459#issuecomment-440732841), you can verify once the PR is ready!

**Comment by valeriocos** [comment]
Yes, sure @harshalmittal4, thanks! 
I was able to reproduce the issue locally, if it can be useful for you I'm going to add the steps to reproduce it (basically the from-date param) and the failing comment asap (my github rate limit token expired and I'm waiting for its regeneration)

**Comment by valeriocos** [comment]
The conf to reproduce quickly the error is:
```perceval github Cloud-CV EvalAI
--category pull_request
--sleep-for-rate
-t xxxx
--from-date 2018-11-22
```

Find below the failing doc:
```
{
    "_links": {
        "html": {
            "href": "https://github.com/Cloud-CV/EvalAI/pull/1853#discussion_r227004241"
        },
        "pull_request": {
            "href": "https://api.github.com/repos/Cloud-CV/EvalAI/pulls/1853"
        },
        "self": {
            "href": "https://api.github.com/repos/Cloud-CV/EvalAI/pulls/comments/227004241"
        }
    },
    "author_association": "NONE",
    "body": "Done.",
    "commit_id": "19b633e5ebea81910e94cedf99ed8024e7d0503b",
    "created_at": "2018-10-22T14:30:00Z",
    "diff_hunk": "@@ -92,7 +92,7 @@\n                                             <td ng-if=\"key.publication_url == ''\"> None </td>\n \n                                             <td class=\"val-style capitalize\" ng-class=\"key.status\">{{key.status}}</td>\n-                                            <td class=\"align-center\">{{key.execution_time}}</td>\n+                                            <td class=\"align-center\" ng-show=\"key.execution_time > 0\">{{key.execution_time}}</td>",
    "html_url": "https://github.com/Cloud-CV/EvalAI/pull/1853#discussion_r227004241",
    "id": 227004241,
    "in_reply_to_id": 226875457,
    "node_id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIyNzAwNDI0MQ==",
    "original_commit_id": "e9b4757ea1fba3b34d474d53fd22b7a0f1c05b7a",
    "original_position": 5,
    "path": "frontend/src/views/web/challenge/my-submission.html",
    "position": null,
    "pull_request_review_id": 166946801,
    "pull_request_url": "https://api.github.com/repos/Cloud-CV/EvalAI/pulls/1853",
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/Cloud-CV/EvalAI/pulls/comments/227004241/reactions"
    },
    "updated_at": "2018-11-22T01:24:29Z",
    "url": "https://api.github.com/repos/Cloud-CV/EvalAI/pulls/comments/227004241",
    "user": null
}
```

**Comment by harshalmittal4** [comment]
Thanks @valeriocos, this will be useful! I will look into this.

**Comment by harshalmittal4** [comment]
Hey @valeriocos, sorry for the delay, I had some college stuff submission. Please review the changes.
