### ISSUE TITLE
Displaying available options for the --category param in the help message specific for each backend..

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-perceval#511]
Currently the **help message for the backends** shows the param `--category` as a general argument, without showing the available options. While to make it more user-friendly, we can show the different available options for the param `--catagory` in the help message specific to each backend, something like:
<br>
```
--category CATEGORY   type of the items to fetch ("issue", "pull_request", "repository")
```
in case of Github.
<br>
```
--category CATEGORY   type of the items to fetch ("issue", "merge_request")
```
in case of Gitlab.

This would add the param `--category` to the `<backend> arguments` group. It is presently under  the `general arguments` group.
<br>
Just a suggestion :slightly_smiling_face:, what do you think @valeriocos, @jgbarah, @sduenas.

**Comment by valeriocos** [comment]
Thank you for proposing this idea @harshalmittal4 . Before deciding how to proceed with this, I would suggest you to finalize the PRs #508 #508 to avoid having pending work, which might be postponed if we started working on new things :)

**Comment by harshalmittal4** [comment]
@valericos, done with those PR's, please review when you get time.

**Comment by valeriocos** [comment]
Thank you @harshalmittal4 . I like the idea so: +1, let's wait for @jgbarah and @sduenas feedback

**Comment by sduenas** [comment]
Yeah, to have it will be awesome.

**Comment by valeriocos** [comment]
@harshalmittal4 feel free to start working on the PR when you have time, thanks!

**Comment by sduenas** [comment]
@harshalmittal4 thanks for the patch. I've just merged it. There are some other repositories that should be also updated:

https://github.com/chaoss/grimoirelab-perceval-mozilla
https://github.com/chaoss/grimoirelab-perceval-opnfv
https://github.com/chaoss/grimoirelab-perceval-puppet

It will be great if you can update them too!

**Comment by valeriocos** [comment]
@harshalmittal4 let me know if you can modify the above repos. In case you are busy, I can do take care of them.

Thanks!

**Comment by harshalmittal4** [comment]
Sure @valeriocos, I aleready made the fork and would produce the PR by today ;)

**Comment by valeriocos** [comment]
great! thanks for the quick reply!
