### ISSUE TITLE
Regarding the metric definition for pull_request_participants

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-perceval#514]
While trying to implement pull_request_participants (for a microtask), I realised that some elaboration is needed on who all are to be considered as participants in a pull_request.

Participants can be defined as those who review a PR **or** comment on a PR **or** both (anyone who either reviews or comments on a PR).
I feel it should be the last option, i.e. anyone who either reviews or comments on a PR is a participant.

The github's API response for pull_requests includes only the reviewers and not commentators. But it contains the url to the comments, using which commentators can be fetched for the metric pull_request_participants using python's requests.

Would this be the right way going for the metric pull_request_participants..just needed your thoughts on this @valeriocos @jgbarah @aswanipranjal,
Thanks!

**Comment by harshalmittal4** [comment]
The issues which are actually pull_requests, include the comments, but the reviews aren't included in this case which is why we can't use them directly.

**Comment by valeriocos** [comment]
@harshalmittal4 I'm not sure this issue should have been opened in the perceval repo, since it seems more a question regarding a specific microtask. 

To answer your question, you are free to include any information which is not provided by Perceval. However, note that if you plan to include this info to Perceval, it should be done as discussed at: https://github.com/chaoss/wg-gmd/issues/81#issuecomment-482813346.

please @jgbarah @aswanipranjal share you thoughts.

Thanks!

**Comment by harshalmittal4** [comment]
Hey @valeriocos I realised this issue is more suited to wg-gmd repo :sweat_smile: 
(But since now it is present here, may I ask about it here)

I tried getting the comments from the url using python's requests, but after certain time it is asking for authentication, so had to provide access_token again to fetch the comments seperately. Will push it by today (after adding some other stuff), for you to have a look just in case.

So already including the comments in perceval's response for category pull_request may be good..
@jgbarah, @aswanipranjal, please share your views ;)

**Comment by valeriocos** [comment]
please close this issue @harshalmittal4 and open it in wg-gmd. For related technical details, we can keep talking here: https://github.com/chaoss/grimoirelab-perceval/issues/515

Thank you :)
