### ISSUE TITLE
[feature] Include comments from /reviews in pull_request fetched by Perceval

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-perceval#516]
The raw pull request data Perceval fetches from /pull/<number> has several attributes, like, the number of review comments, commits, etc. 
which are missing for the comments present at /reviews.  This feature includes the missing comments as "reviews"

The discussion started [here](https://github.com/chaoss/wg-gmd/issues/81#issuecomment-482809284
).

My current plan: 
1. In the [pulls function (github.py)](https://github.com/chaoss/grimoirelab-perceval/blob/b5dec01c90407e28efce2a04a4b8a9d5bfedf0e6/perceval/backends/core/github.py#L600), to the raw pull data fetched from the fetch() method, add keys similar to the already present data, like the reviews link and the number of reviews.

2. Create corresponding functions to add values to the "reviews_data" key, similar to other types of comments fetched, like pull_reviews() and _get_pull_reviews() in github.py

@valeriocos, let me know if I misunderstood anything or if something needs more clarity.

**Comment by valeriocos** [comment]
Yes, the plan looks good. To add more info, which may help you in the implementation, you should:

- add `reviews` to the list [TARGET_PULL_FIELDS](https://github.com/chaoss/grimoirelab-perceval/blob/b5dec01c90407e28efce2a04a4b8a9d5bfedf0e6/perceval/backends/core/github.py#L61)
- add another elif statement [here](https://github.com/chaoss/grimoirelab-perceval/blob/b5dec01c90407e28efce2a04a4b8a9d5bfedf0e6/perceval/backends/core/github.py#L287) to include reviews, for instance: 
```
...
elif field == 'reviews':
     pull[field + '_data'] = self.__get_pull_reviews(pull['number'])
...
``` 
- write the backend method `__get_pull_reviews(pr_number)`, similar logic can be found [here](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L405)
- write the client method `pull_reviews(pr_number)`, similar logic can be found [here](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L653)
- write tests (please have a look at [test_fetch_pulls](https://github.com/chaoss/grimoirelab-perceval/blob/b5dec01c90407e28efce2a04a4b8a9d5bfedf0e6/tests/test_github.py#L255) and [test_pull_review_comments](https://github.com/chaoss/grimoirelab-perceval/blob/b5dec01c90407e28efce2a04a4b8a9d5bfedf0e6/tests/test_github.py#L2408))

Thank you @Polaris000 :)

**Comment by Polaris000** [comment]
I have pushed the changes to my fork of grimoirelab-perceval [here](https://github.com/Polaris000/grimoirelab-perceval/tree/PullRequestReviews_branch). 
Only thing I have n't done yet is the tests part. 

Should I still open a pull-request now and then add tests later? 
Or will you check my fork and then I can send everything at once? 

Let me known @valericos, thanks!

**Comment by Polaris000** [comment]
Thanks for the reply @valeriocos (on my fork). I deleted the comment I made in this issue yesterday since right after making that comment, it became apparent to me that it would be much better to review the changes in a pull request rather than elsewhere. 

I am working on the tests now. 

Very sorry for the delay. Since there are only about 10 days of classes left at my university, several class tests and assignments are due in this week and the next.

**Comment by valeriocos** [comment]
no worries @Polaris000 , feel free to submit the PR when you have time.
Good luck with the last days of classes :)

**Comment by Polaris000** [comment]
@valeriocos, the tests use data from a repository named "repo", owned by "zhquan_example". I am unable to access it. 

I realized that parameters like the rate limit are fetched with respect to example.com but haven't worked with example.com before. 

What am I missing? 
Thanks in advance!

**Comment by harshalmittal4** [comment]
Hey @Polaris000, all the reference data for github tests can be found within [this](https://github.com/chaoss/grimoirelab-perceval/tree/6aa7968f2ecfbc90b64bc81ccfed7f0a4152bea0/tests/data/github) directory :)

**Comment by harshalmittal4** [comment]
Hey @Polaris000, all the reference data for github tests can be found in [this](https://github.com/chaoss/grimoirelab-perceval/tree/6aa7968f2ecfbc90b64bc81ccfed7f0a4152bea0/tests/data/github) directory :)

**Comment by Polaris000** [comment]
Thanks for the reply @harshalmittal4. I am aware of that. The feature I need to test requires data from elsewhere, which is why I raised the question.

**Comment by valeriocos** [comment]
Tests against APIs (like GitHub, GitLab) rely on `httpretty`, which is a HTTP client mocking tool for Python.

If we focus on the following test:
https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_github.py#L176, you can see that from line 180 - 232, we are setting up the mocked data (for given URLs, some predefined data is returned). To enable httpretty, it is needed to add `@httpretty.activate` on top of the method.

**Comment by Polaris000** [comment]
But where do you get the mocked data from?
For example, the file github_issue_comments_1 contains issue comments. But how were they fetched?

**Comment by harshalmittal4** [comment]
Yes @Polaris000, I also required the mocked data for commit comments (sorry I understood your question late as soon as I made the reply!).
Hey @valeriocos, how can we get the mocked data for reviews and commit comments respectively..

**Comment by valeriocos** [comment]
Sorry @Polaris000 I misunderstood your question.

You can take it directly from the GitHub API via `curl` or using perceval. In the latter case, once a feature is ready, you can launch perceval (with the new feature) on a given repo and add some code to print the results of the API. For instance, if we want to get some test data for issue comments we can modify the method `__get_issue_comments` in the following way:
```
    def __get_issue_comments(self, issue_number):
        """Get issue comments"""

        comments = []
        group_comments = self.client.issue_comments(issue_number)

        for raw_comments in group_comments:

            for comment in json.loads(raw_comments):

                print(json.dumps(comment, sort_keys=True, indent=4)) <----------------------

                comment_id = comment.get('id')
                comment['user_data'] = self.__get_user(comment['user']['login'])
                comment['reactions_data'] = \
                    self.__get_issue_comment_reactions(comment_id, comment['reactions']['total_count'])
                comments.append(comment)

        return comments
```

You can then copy the printed content to a file (together with other comments if needed).

**Comment by harshalmittal4** [comment]
>Sorry @Polaris000 I misunderstood your question.

Me too!

Regarding the data, does it not need to be aligned with the "zhquan_example", I mean can it be from any repo, 
@valeriocos, please see, need some guidance, thanks!

**Comment by valeriocos** [comment]
yes, sure, it is not needed to be aligned with that repo

**Comment by valeriocos** [comment]
@Polaris000 let me know when I can review your work (either in your repo or on your upcoming PR), thank you!

**Comment by Polaris000** [comment]
@valeriocos, since pull_request "reviews" are now included in the pull request data fetched by perceval, every test using the data from zhquan_example would fail, since there are no reviews for that. 

The test_reviews() test which I have written compares the reviews fetched by perceval with the reviews for a grimoirelab-tutorial pull request. Of course,  this test is passed, but any test dealing with data for an entire pull request fails (the tests use zhquan_example/repo data). 

The only solution I can come up with is to completely update all github test data and change all the global constant urls in test_github.py to account for the changed test data. 

Let me know what you think. 
> @Polaris000 let me know when I can review your work (either in your repo or on your upcoming PR), thank you!

I am done with implementing the feature and adding a test_reviews which the code passes. But as explained above, a few other tests give errors, like the following: 

```
equests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/chaoss/grimoirelab-tutorial/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 502 error responses',))

```
