### ISSUE TITLE
[github] Add GitHub release data collection (or Git branch/tag information)

### ISSUE THREAD

**Issue by paultyng** [chaoss/grimoirelab-perceval#520]
In addition to issues / commits from GitHub, it would be nice to be able to correlate releases with certain activity (forum traffic, etc).

**Comment by valeriocos** [comment]
Thank you @paultyng for your interest in Perceval. Please, could you elaborate a bit more on your feature request and clarify the terms below ?

- Does the term `release` refer to this endpoint: https://developer.github.com/v3/repos/releases/ or to git branches/tags ?
- Does forum traffic is related to this endpoint: https://developer.github.com/v3/repos/traffic/ or to other data sources (maybe already covered by Perceval) ?

Thanks

**Comment by sduenas** [comment]
As Valerio said, this ticket is not elaborated enought. I'm closing it. Feel free to reopen it with an improved description of the requirements.
