### ISSUE TITLE
[Question] how to use supybot backend

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#537]
Hi, I'm trying to get any data from `supybot` Perceval data source, but I always get 0 messages.
I've read the class documentation and tried many many different URLs and I'm unable to fetch anything.
For example, I'm trying to get data from `#zephyrproject` channel on `irc.freenode.net`server.
No luck, tried:
```
perceval supybot 'irc://irc.freenode.net/#zephyrproject' ircdir
perceval supybot 'irc://irc.freenode.net/zephyrproject/' ircdir
perceval supybot 'irc.freenode.net/#zephyrproject' ircdir
perceval supybot 'irc.freenode.net/zephyrproject/' ircdir
perceval supybot 'http://irc.freenode.net/#zephyrproject' ircdir
perceval supybot 'http://irc.freenode.net/zephyrproject/' ircdir
perceval supybot 'http://webchat.freenode.net/zephyrproject' ircdir
perceval supybot 'http://webchat.freenode.net/zephyrproject/' ircdir
perceval supybot 'http://webchat.freenode.net/#zephyrproject' ircdir
perceval supybot 'http://webchat.freenode.net' 'zephyrproject'
perceval supybot 'http://webchat.freenode.net' '#zephyrproject'
```
No idea what is wrong.
Always getting the response:
```
[2019-06-18 07:28:23,205] - Sir Perceval is on his quest.
[2019-06-18 07:28:23,206] - Fetching messages of 'irc://irc.freenode.net/#zephyrproject' from 1970-01-01 00:00:00+00:00
[2019-06-18 07:28:23,207] - Fetch process completed: 0 messages fetched
[2019-06-18 07:28:23,207] - Sir Perceval completed his quest.
```
I was trying to figure out things from [this file](https://buildmedia.readthedocs.org/media/pdf/perceval/latest/perceval.pdf) and the last argument is a directory to retrieve/store log files. Am I supposed to fetch that logs manually? And datasource works only then? If so, then how can I fetch those logs?

Documentation is not clear about for example protocol name: shoudl I put `irc://` or use `http(s)://`address. webchat.freenode.net is using captcha (HTTP client) - is grimoirelab Perceval trying to go around somehow, or is it using other access modes? Is it using some random/anonymous user?

Can you provide at least one working example of this data source? Or for every data source in general? If data source requires any username/password/API token/ssh public key etc - then it would be nice to have documentation describing how to get those credentials?

**Comment by sduenas** [comment]
Supybot backend doesn't download anything. It only analyzes files from a local directory. You have to have your own process to download the archives or to provide them to Perceval.

Sorry if the documentation is not clear about it.

**Comment by lukaszgryglicki** [comment]
OK, that clear - would be great to have that info in the docs.

**Comment by lukaszgryglicki** [comment]
Do you have any suggestions about tools to download IRC logs? Obviously, somebody who created that data source must have something to get that data - would be great to have that example in the docs as well.

**Comment by sduenas** [comment]
Well, `supybot` is the name of the bot that generates those data :). So, if the bot is subscribed to that channel, it can generate and store the logs wherever you need them.

**Comment by lukaszgryglicki** [comment]
Ok, so data source only supports IRC channels that have that bot installed. Also, a good candidate to add to the docs. I guess I cannot install that bot on every repo that I want to track, so this is a bit unusable for me atm. Thanks for the info.

**Comment by lukaszgryglicki** [comment]
Correct me if I'm wrong, i want to 100% confirm: to have `supybot` data source working I have to ask every single IRC channel owners to install the additional bot on their channels, right?

**Comment by sduenas** [comment]
The only way to get data from IRC channels (as far as I know) is to have something listening on those channels. Either you or the admins of the channel should have a user/bot listening there to get the data. Admins used to have that and `supybot` was the most common some years ago.

Supybot produces a specific output format. If data was generated by other bot, you will have to create something to translate from that format to supybot one, or to create a backend to parse that data.
