### ISSUE TITLE
[Question] How to use meetup backend tokens?

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#541]
Hi, I'm wondering how to set up meetup token to be used for Perceval.
[Here](https://github.com/LF-Engineering/perceval-scripts#meetups) I'm trying to get Hyperledger meetup data using Perceval. I'm running this without tokens via: `perceval meetup --sleep-for-rate hyperledger`.
BTW: how should I set `--min-rate-to-sleep MIN_RATE_TO_SLEEP` parameter? I just want it to wait until rate limit is reset.
I've created a meetup account and then wanted to create OAuth token (just like in GitHub backend case).  But after reading [their documentation](https://www.meetup.com/meetup_api/auth) it only seems that `OAuth2` is supported, now see [this](https://www.meetup.com/meetup_api/auth/#oauth2). How can I create a single token string to be used by Perceval's `-t API_TOKEN` argument?
Would be great to have at least one example of how to use this and also other data sources. Most of the data sources that I've been working today are not documented and it is extremely hard to dive into details about what "group" is (an URL, an org name, a group/meetup name?), what is a token? How to create a token? This is a shared set of missing documentation data for almost all backends.

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki , you can get an API token for meetup on this page: https://secure.meetup.com/meetup_api/key/

Then, you can execute perceval in the following way:
 ```
perceval meetup BostonRust -t 237c45d... --sleep-for-rate
```

**Comment by lukaszgryglicki** [comment]
Hi, I've tried this before creating an issue:
![Screenshot 2019-06-18 at 16 02 26](https://user-images.githubusercontent.com/2469783/59690934-874b3480-91e2-11e9-9698-d3e9f0ae1a3e.png)

**Comment by valeriocos** [comment]
![captura-07](https://user-images.githubusercontent.com/6515067/59691130-d729fb80-91e2-11e9-86ea-36777e3d4a87.png)

Interesting, in my case I can still get the API Key. We will look into this and update you, thanks!

**Comment by lukaszgryglicki** [comment]
Thanks, I cannot do it. Tried different browsers. maybe this is because of a new account created specially for this?

**Comment by valeriocos** [comment]
Yes, it seems so, I've just created an account and got the same result you posted:
![captura-09](https://user-images.githubusercontent.com/6515067/59691772-de053e00-91e3-11e9-98b5-accb96c2474b.png)

**Comment by lukaszgryglicki** [comment]
Great that you can replicate, now I see a problem because OAUth2 seems to be a lot more complex to handle in a simple python command like `perceval`. it requires server callbacks etc. So my question is: is the `meetup` backed dead for now?

**Comment by valeriocos** [comment]
In the case you don't have a previous account, the answer is yes. In any case, this is going to bite as soon, we should provide a quick fix @sduenas

**Comment by lukaszgryglicki** [comment]
I don't have an old meetup account, so, unfortunately, it is dead for me :-(

**Comment by valeriocos** [comment]
Can we close this issue @sduenas @lukaszgryglicki  ?

**Comment by lukaszgryglicki** [comment]
I think we should wait for meetup OAuth support PR to be merged and make sure docs are updated. But this is only my opinion.

**Comment by valeriocos** [comment]
PR merged: https://github.com/chaoss/grimoirelab-perceval/pull/544

@lukaszgryglicki @sduenas if it's OK on your side, we could close this issue, thanks

**Comment by lukaszgryglicki** [comment]
OK to close.
