### ISSUE TITLE
[Feature request] Add support for OAuth2 in meetup backend

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#542]
This is a follow up from [this issue](https://github.com/chaoss/grimoirelab-perceval/issues/541). Meetup API keys are deprecated, and new accounts no longer have the option to create API keys (old account still can do it). Meetup forces to use `OAuth2` instead.

**Comment by valeriocos** [comment]
a WIP PR is available at: https://github.com/chaoss/grimoirelab-perceval/pull/544. The creation of an oauth token is assisted by a script: https://gist.github.com/valeriocos/e16424bc7dc0f2d6dd8bb9295c6f9a4b

**Comment by lukaszgryglicki** [comment]
Wow, this is fast, but you need some service running on your own domain `https://example.com` listening for call-backs right?

**Comment by valeriocos** [comment]
it seems that it's not needed, afaiu the `redirect_uri` is needed just to get the code, which will appear as a param of the redirect_uri. I tried with `https://example.com/test` as `redirect_uri` and got this `https://example.com/test?code=683f3ebe...`

**Comment by lukaszgryglicki** [comment]
OK, I'll check.

**Comment by lukaszgryglicki** [comment]
@valeriocos if I save your gist python says:
```
  File "./meetup_create_token.py", line 42
    print("Access https://secure.meetup.com/meetup_api/oauth_consumers and create a consumer (if you don't have it)")
        ^
```
You have broken whitespace in your example. I'll fix this locally, but I'm just letting you know.

**Comment by lukaszgryglicki** [comment]
My fixed version is:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015-2019 Bitergia
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA.
#
# Authors:
#     Valerio Cosentino <valcos@bitergia.com>
#

import json
import requests

OAUTH2_TOKEN = 'https://secure.meetup.com/oauth2/access'

def get_token(client_id, client_secret, redirect_uri, code):
    access_uri = "{}?client_id={}&client_secret={}&redirect_uri={}&code={}&grant_type=authorization_code".format(OAUTH2_TOKEN,
        client_id,
        client_secret,
        redirect_uri.strip("\""),
        code
    )
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'application/json'
    }
    r = requests.post(access_uri, headers=headers)
    r_json = r.json()
    print(json.dumps(r_json, sort_keys=True, indent=4))

def main():
    print("Access https://secure.meetup.com/meetup_api/oauth_consumers and create a consumer (if you don't have it)")
    print("Replace YOUR_CONSUMER_KEY and YOUR_CONSUMER_REDIRECT_URI with the correct info in the link below")
    print("https://secure.meetup.com/oauth2/authorize?client_id=YOUR_CONSUMER_KEY&response_type=code&redirect_uri=YOUR_CONSUMER_REDIRECT_URI")
    print("If everything goes OK, you will get a code as param of YOUR_CONSUMER_REDIRECT_URI, for instance: https://example.com/test?code=683f3ebe84bf867d2b8d591faa389ed5")
    print("Use this code, together with your client key, secret, redirect URI to get an access token")
    client_id = input('Enter your client key: ')
    client_secret = input('Enter your client secret: ')
    redirect_uri = input('Redirect URI: ')
    code = input('Code: ')
    print("***** ***** ***** *****")
    get_token(client_id, client_secret, redirect_uri, code)
if __name__ == "__main__":
    main()
```

**Comment by valeriocos** [comment]
Thanks @lukaszgryglicki , I have just updated the gist

**Comment by lukaszgryglicki** [comment]
Your code works:
```
{
    "access_token": "redacted",
    "expires_in": 3600,
    "refresh_token": "redacted",
    "token_type": "bearer"
}
```

It says `expires_in`: `3600`. Does it mean that I have to run this python shell every hour?

**Comment by lukaszgryglicki** [comment]
Also, this code is one time, only, the next time you run this, the code is invalid, so you have to reauthenticate using browser. I see no easy way to automate this from a shell script, I've tried:
```
#!/bin/bash
cat /etc/meetup/key /etc/meetup/secret /etc/meetup/redirect_uri /etc/meetup/code | ./meetup_create_token.py
```
But this works only once, and only when you generated the code from the browser.
How do you imagine to use meetup backend "headless" I mean running somewhere from the Kubernetes cron job for example?

**Comment by lukaszgryglicki** [comment]
I would rather think about passing all stuff needed to generate `OAuth2` token (which is `key` and `redirect_uri`) generating code, then using all 4 items (key, secret, redirect_uri and code) to get a token. All of this should happen automatically, without the need to use any manual steps.  I can accept manual steps, even complex if they need to be done once, but if this is needed every hour then we need to automate this, otherwise `meetup` backend is unusable from shell scripts, cron jobs or Kubernetes.

**Comment by valeriocos** [comment]
Thank you for your feedback @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
You're welcome.

**Comment by valeriocos** [comment]
@lukaszgryglicki I have been testing the use of the same oauth token on different days and with a battery of meetup groups (around 120). The token doesn't seem to expire, so I'm not sure the param `expires_in` is active. 

I also had a look at the [RFC](https://tools.ietf.org/html/rfc6749#section-4.2.2), from the description below , it may be possible that what we see it's the default value, which is finally ignored.
```
expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.
```

If the assumptions above are correct, once the access token has been generated you can use it directly within the perceval backend (without the need of adding the logic to generate a new token).

**Comment by lukaszgryglicki** [comment]
Ok, I will try to generate another one and just use it, and then let you know. Thanks.
