### ISSUE TITLE
[Feature request] Add support for Rocket.Chat

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#543]
Hi, any chance to add backend support for Rocket.Chat, for example, to be able to get data from https://chat.hyperledger.org.
Thanks, best regards.

**Comment by sduenas** [comment]
I don't think this is under our plan yet but PRs are always welcome.

**Comment by lukaszgryglicki** [comment]
Ok, so I'll ask my team if they want me to implement this.
