### ISSUE TITLE
[Question] How to use discourse tokens?

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#545]
Suppose I want to get discourse data, I can do it tokenless via: `perceval discourse https://edgex.discourse.group`, but I expect to hit some rate limit or be banned by IP or whatever after some time.

The documentation says that I can use token.

I'm going to `https://edgex.discourse.group` site, create an account and then I want to create a token, but I don't see any option to create token there.
Can anybody (like backend author) point me to some instructions about how to create such a token?

Additionally:
-----------------------------
I suggest that every single data source (there are 29 currently) should have its own `example` section in the documentation, describing step-by-step how to get data from a single example source.
- This will make it a lot easier to use
- This will probably detect some bugs or outdated data sources (I've already detected meetup as outdated)
- This will make sure what specific parameters value should be (usually group, URL, resource, etc - it is never clear if we should put URL there, or project name uppercase/lowercase or some custom resource definition separated by hyphens or dots or whatever)
- Some additional parameters - like some data sources require at least 1 argument, other require two, etc (this will make it a lot clearer)
- Finally, many data sources use some authentication (API keys, tokens, usernames, passwords, SSH public keys and more). We should have a clear example of how to create them and then how to provide them (for example GitHub backend supports multiple tokens, I've implemented this myself).
------------------------------

**Comment by sduenas** [comment]
> Suppose I want to get discourse data, I can do it tokenless via: `perceval discourse https://edgex.discourse.group`, but I expect to hit some rate limit or be banned by IP or whatever after some time.
> 
> The documentation says that I can use token.
> 
> I'm going to `https://edgex.discourse.group` site, create an account and then I want to create a token, but I don't see any option to create token there.
> Can anybody (like backend author) point me to some instructions about how to create such a token?

From[ Discourse documentation](https://docs.discourse.org/), under **Authentication** section:

```
To become authenticated you will need to create an API Key from the admin panel.
```

> ## Additionally:
> 
> I suggest that every single data source (there are 29 currently) should have its own `example` section in the documentation, describing step-by-step how to get data from a single example source.
> 
>     * This will make it a lot easier to use
> 
>     * This will probably detect some bugs or outdated data sources (I've already detected meetup as outdated)
> 
>     * This will make sure what specific parameters value should be (usually group, URL, resource, etc - it is never clear if we should put URL there, or project name uppercase/lowercase or some custom resource definition separated by hyphens or dots or whatever)
> 
>     * Some additional parameters - like some data sources require at least 1 argument, other require two, etc (this will make it a lot clearer)
> 

Most of these answers can be answered either reading the README file or running `perceval <backend> --help`, but of course, it needs a lot of improving.

>     * Finally, many data sources use some authentication (API keys, tokens, usernames, passwords, SSH public keys and more). We should have a clear example of how to create them and then how to provide them (for example GitHub backend supports multiple tokens, I've implemented this myself).

README file contain info for those backends where authentication methods are more complicated than others. I'd like to have a good manual for Perceval but so far, we couldn't find time to write it.

Thanks for your comments, anyway. We'll take into account and any help is always welcome.

**Comment by lukaszgryglicki** [comment]
Thanks for the info. I have no time to dive into it during the current or maybe even next week :(, but there was no admin panel at all AFAIR.

**Comment by sduenas** [comment]
I think to see the admin panel you need special permissions. You would have to ask the token to the admin of the site, I think.

I'm closing this issue. Feel free to open it if you have more troubles about it.
