### ISSUE TITLE
Index Gerrit hashtags

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-perceval#561]
Gerrit allows to add so-called "Hashtags" to changesets: https://gerrit-review.googlesource.com/Documentation/intro-user.html#hashtags

They are currently not indexed in the DB (according to Kibana's "Discover") but probably could be.

**Comment by sduenas** [comment]
Perceval parses everything that goes in the JSON obtained from gerrit. This is not a bug.
