### ISSUE TITLE
Perceval github with --fetch-archive (when there is no archive yet) fails

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#585]
I want to execute `perceval github` on some repo periodically. I don't want it to redo its full analysis every time. This seems to work OK when running without `--from-archive` for the first time and then subsequent runs can use `--from-archive` flag (to save time processing data already processed), but when I try to run with `--from-archive` when perceval was never run before:

`perceval github --category repository LF-Engineering sync-data-sources -t  xyz --fetch-archive --sleep-for-rate`:
```
[2019-11-09 13:34:43,582] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 609, in run
    self._log_summary(big.summary)
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 662, in _log_summary
    'total': summary.total,
AttributeError: 'NoneType' object has no attribute 'total'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/repos/grimoirelab-perceval/bin/perceval", line 157, in <module>
    main()
  File "/repos/grimoirelab-perceval/bin/perceval", line 103, in main
    cmd.run()
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 613, in run
    raise RuntimeError(str(e))
RuntimeError: 'NoneType' object has no attribute 'total'
```

Is there a way to run a single `perceval` command that will figure out if there is data already and either get all data from scratch (when there is no data yet) or just continue from where it left the last time?

Same for all other data sources? Is there any generic option to handle that? I see that `perceval git` has `--latest-items` flag, how about other data sources? Do I have to run help on every single one of them and try to figure out what is the "resume" flag name for each?

BTW: `perceval datasource` lists data source command-line options, but nothing more, I have to guess by name what all those options do....is there any documentation that describes each data source all options - what they do?

**Comment by lukaszgryglicki** [comment]
BTW: is `--fetch-archive` actually doing what I think it does?
My understanding is that it fetches whatever was already processed from its SQLite archives database *and then fetches new GitHub data for newer activity*, right?

**Comment by lukaszgryglicki** [comment]
cc @valeriocos @sduenas

**Comment by lukaszgryglicki** [comment]
The conclusion is that I can resume `perceval git` during the next run (so it only fetches new data since then) via `--latest-items` flag - this works.

But for GitHub `perceval github` there is no such flag, the closest thing I’ve found is `--fetch-archive` but this behaves like this:
My local perceval version (older) receives nothing when run with this flag for the first time, the newest version panics/errors in this case.

Running `perceval github` without this flag gets all data, but always processes all data from repo history, it doesn’t resume during the subsequent runs, so there is no way to let it fetch most data once and then only update daily for instance.

If after fetching all data without `--from-archive` I call `perceval github` with `--fetch-archive` flag - it will only fetch the data from last run, even if new data were added on GitHub since then (so it seems to only read data from disk and nothing more).

There is also a flag `--from-date`, but how can I know what is the last date that I have data for? 

Probably I can run in 2 approaches:
1 = FULL which will attempt to collect all data for all endpoints in all data sources without any resuming/caching/archives.

2 Then (say next day) with special flag START_DATE that will be passed to all endpoints. But in this case, if anything failed during the first (1) FULL run, the `FROM_DATE` run will never fix that.

Why the `perceval` doesn’t have a flag that will just read its own last output for given repo (it is saved in `~/.perceval`) and then automatically continue from there?

**Comment by sduenas** [comment]
Perceval doesn't have that feature but in the case of Git. The archive is only conceived for testing purposes and not as a source of truth.
Perceval doesn't resume because it lets others to decide whether the downloaded data was valid or not. If you need something to do this work, use Arthur.

The only exception we have is with git due to how it works internally returning data when `git log` is called. It's possible that you don't get all the items added after a certain date.

**Comment by lukaszgryglicki** [comment]
OK, I've used `p2o.py` instead, it uses `ES` when running multiple times.
