### ISSUE TITLE
meetup backend is not working

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#588]
When you try to use `meetup` backend, it returns permission error (with correct `-t TOKEN`).
I was thinking that the token is incorrect and tried to create a new one.
Token authorization is no longer supported, see:
![Screenshot 2019-11-11 at 09 04 50](https://user-images.githubusercontent.com/2469783/68571274-e8f68e80-0462-11ea-8ee9-bdd811a7be88.png)

**Comment by valeriocos** [comment]
@lukaszgryglicki you should generate an oauth2 token. You can use the following script:
https://gist.github.com/valeriocos/e16424bc7dc0f2d6dd8bb9295c6f9a4b.

Let us know if this solves your issue, thanks!

**Comment by valeriocos** [comment]
@lukaszgryglicki feel free to reopen the issue if needed

**Comment by lukaszgryglicki** [comment]
So I need some URL registered right? If I put some example URL it fails due to callback URL not found error.

**Comment by valeriocos** [comment]
Have you tried to use `"https://example.com/test"` has callback?

**Comment by lukaszgryglicki** [comment]
No, I will, thanks.

**Comment by lukaszgryglicki** [comment]
`https://example.com/test` work and returns:
```
***** token *****
{
    "access_token": "(redacted)",
    "expires_in": 3600,
    "refresh_token": "(redacted)",
    "token_type": "bearer"
}
```

But it says refresh in `3600s` - does it mean that I need to do this every 1 hour? It's a manual operation requiring user action so not practical at all. 
Or maybe I can ignore this "expires in"?

**Comment by valeriocos** [comment]
You can ignore it.

We investigated `expires_in` in the past and it's not used/active. We are using oauth2 tokens in our prd envs and the collection runs smoothly.

Hope it helps

**Comment by lukaszgryglicki** [comment]
Yes, thank you very much, so I should be good to go, but cannot spot check now, due to big data collection already running for 3150 endpoints.
