### ISSUE TITLE
Investigate support for Jenkins pipelines

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#596]
After checking the issue #591 with @sduenas, it seems that Jenkins may return jobs of different types. For instance, here https://jenkins.zowe.org/, the jobs below are related to  multibranch pipelines.

- https://jenkins.zowe.org/job/zowe-dockerimage-test/ (not configured)
- https://jenkins.zowe.org/job/zowe-docs-site/ (a job inside)
- https://jenkins.zowe.org/job/zowe-helloworld-jjb/ (not configured)

The idea is check whether the API allows to retrieve builds inside multibranch pipelines.

**Comment by sduenas** [comment]
This was already fixed by #597
