### ISSUE TITLE
commits count

### ISSUE THREAD

**Issue by musman-ashraf** [chaoss/grimoirelab-perceval#601]
Hi,
I noticed a difference between commits mentioned on GitHub and when I fetched through perceval (always more). Why is that?

Thanks in advance.

**Comment by jgbarah** [comment]
Could this explain it?:

> "The statistics exposed by the API match the statistics shown by different repository graphs. [...] All statistics exclude merge commits."
> (From ["Statistics" in GitHub API docs](https://developer.github.com/v3/repos/statistics/#statistics-exclude-some-types-of-commits)).

If that's not the case, please provide an specific example.

**Comment by musman-ashraf** [comment]
Thanks. It says, "All statistics exclude merge commits",  yet there are some linked commits to pull request which are part of statistics and some are not.

**Comment by jgbarah** [comment]
Yes. Perceval fetches all commits in the repository, except that a branch is specified, in which case only commits in that branch are fetched.

**Comment by musman-ashraf** [comment]
Thanks a lot.

**Comment by jgbarah** [comment]
Thanks to you for caring!

Can we close this issue then?

**Comment by sduenas** [comment]
Yeah. I think this is already resolved.

**Comment by sduenas** [comment]
By the way, for completion, GitHub only shows the number of commits from `master` (or the default branch), not from other branches.
