### ISSUE TITLE
Readthedocs not updated properly

### ISSUE THREAD

**Issue by abhiandthetruth** [chaoss/grimoirelab-perceval#625]
For example, the Github backend categories, checkout below links for differences
https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L48
https://perceval.readthedocs.io/en/latest/perceval.backends.core.html#module-perceval.backends.core.github

**Comment by valeriocos** [comment]
@jgbarah do you know when the readthedocs is updated (e.g., when the package is uploaded to pypi)?

**Comment by vchrombie** [comment]
The GitHub Webhook is resynced and the configuration files are also updated. The documentation will be built every time there is a change in the source code.

The docs can be accessed at [perceval.readthedocs.io](https://perceval.readthedocs.io).

The issue is resolved.
