### ISSUE TITLE
[Feature Request] Add support for Gitter backend

### ISSUE THREAD

**Issue by animeshk08** [chaoss/grimoirelab-perceval#631]
[Gitter](https://gitter.im/) is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.

It would be a good idea to include Gitter as a backend for Perceval.

The API documentation of Gitter can be found here: https://developer.gitter.im/docs/rest-api

**Comment by valeriocos** [comment]
I like the idea @animeshk08! While waiting for others to comment on this issue, please can you start having a look at the API and check which data could be extracted (a couple of target Gitter instances can be useful to test the code too)?

Thanks

**Comment by animeshk08** [comment]
Hi, I have had a look at the API documentation of Gitter.
We can fetch the messages from a Gitter room, similar to Slack.
The `List Messages` API found [here](https://developer.gitter.im/docs/messages-resource) can be used for that.

However, it does require the `roomid` endpoint which can be found in a way similar to `groupsio` backend where we list the rooms a user has joined using the `List rooms`API found [here](https://developer.gitter.im/docs/rooms-resource) match the room name and get the `roomid` for a room.

In terms of parameters, Perceval can take the `group name`, `room name` and `access token` as the parameters.

Note:
 1. A room belongs inside a group(community) hence a room name will typically be `{groupname}/{roomname}`.
1. An access token is necessary to authenticate yourself to the APIs


Some Gitter instances which can be used for testing may be:
1. https://gitter.im/jenkinsci/jenkins 
1. https://gitter.im/fossasia/fossasia
1. https://gitter.im/openMF/mifos

Please comment here for any suggestion :)

**Comment by valeriocos** [comment]
Thank you @animeshk08 ! Your proposal looks good!

> In terms of parameters, Perceval can take the group name, room name and access token as the parameters.

+1 

> Some Gitter instances which can be used for testing may be:

+1

WRT the authentication, please consider to write a script to get the token (there is something similar for twitter https://gist.github.com/valeriocos/7d4d28f72f53fbce49f1512ba77ef5f6)

I wasn't able to find info about rate limit at https://developer.gitter.im/docs/. Please let me know if you find something, thanks!

**Comment by animeshk08** [comment]
> WRT the authentication, please consider to write a script to get the token (there is something similar for twitter https://gist.github.com/valeriocos/7d4d28f72f53fbce49f1512ba77ef5f6)

Sure! Thank you for the reference.
 
> I wasn't able to find info about rate limit at https://developer.gitter.im/docs/. Please let me know if you find something, thanks!

I also was not able to find any rate limit info. I will ping you in case I have any new findings!!
