### ISSUE TITLE
[backend] Sanitize before archive missing in some backends

### ISSUE THREAD

**Issue by animeshk08** [chaoss/grimoirelab-perceval#638]
The method `def sanitize_for_archive(url, headers, payload)` is used to remove sensitive information like api-token, userid, password, etc from the `url` , `header`, or `payload` before storing it to the archive. This method is missing in a few backends.

**Comment by animeshk08** [comment]
Hi @valeriocos. I had a few doubts with this work:

* This method is not necessary for backends that are not storing items in archive right?
 For instance,
 https://github.com/chaoss/grimoirelab-perceval/blob/791a2d3f92f0b07451fb17160353afbb6aecdee2/perceval/backends/core/groupsio.py#L298

* How can the `api-token/userid/password` be removed from the auth of a session. I don't think `sanitize_for_archive` can be used for that and there are no other alternative methods currently present either(correct me if I am wrong). 
For instance: 
https://github.com/chaoss/grimoirelab-perceval/blob/791a2d3f92f0b07451fb17160353afbb6aecdee2/perceval/backends/core/jenkins.py#L307
https://github.com/chaoss/grimoirelab-perceval/blob/791a2d3f92f0b07451fb17160353afbb6aecdee2/perceval/backends/core/jira.py#L407

**Comment by animeshk08** [comment]
> How can the api-token/userid/password be removed from the auth of a session. I don't think sanitize_for_archive can be used for that and there are no other alternative methods currently present either(correct me if I am wrong).

Okay, I think we are not storing `auth` in the archive. So we don't need to clean it in the first place, my bad.
https://github.com/chaoss/grimoirelab-perceval/blob/791a2d3f92f0b07451fb17160353afbb6aecdee2/perceval/client.py#L190

**Comment by valeriocos** [comment]
Hi @animeshk08 !

> This method is not necessary for backends that are not storing items in archive right?

Yes, it is not needed

> How can the api-token/userid/password be removed from the auth of a session.

Only the `url`, `payload` and `headers` are stored in the archive: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/client.py#L190.

Let me know if you have more questions, thanks!

**Comment by animeshk08** [comment]
Thanks for the clarifications :)
