### ISSUE TITLE
[Travis] upgrade pip and setuptools in perceval-related backends

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#647]
Following https://github.com/chaoss/grimoirelab-perceval/pull/643, the same fix should be applied to the other perceval-related backends:
- https://github.com/Bitergia/grimoirelab-perceval-finos
- https://github.com/chaoss/grimoirelab-perceval-mozilla
- https://github.com/chaoss/grimoirelab-perceval-opnfv
- https://github.com/chaoss/grimoirelab-perceval-puppet

@animeshk08 @ria18405, plese let me know if you plan to submit PRs to these repos, thanks!

**Comment by animeshk08** [comment]
HI @valeriocos. I will get a PR ready!

**Comment by valeriocos** [comment]
Thanks @animeshk08 , (in case it helps) I'm using the following commit title/description:

-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
[travis] Upgrade setuptools and pip

This code upgrades the setuptools and pip. This change
stems from the fix at:
https://github.com/chaoss/grimoirelab-perceval/pull/643.
It was needed to fix the CI tests that were failing due
to the following error:

```
File "../python3.5/site-packages/setuptools/sandbox.py", line 44, in _execfile
  code = compile(script, filename, 'exec')
File "/tmp/easy_install-wu9lgsxc/pandoc-2.0a4/setup.py", line 11
  error = f"pip is not installed, refer to <{url}> for instructions."
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by animeshk08** [comment]
Thanks, @valeriocos. I was going to use the same commit message. :see_no_evil:

**Comment by ria18405** [comment]
Thanks @valeriocos , nice idea. 

I see some PRs have been submitted.Thanks @animeshk08 for helping. I'll be happy to help if any repository is left?

**Comment by valeriocos** [comment]
Hi @ria18405 ! I see that all perceval-related repos are covered. 

The repos https://github.com/chaoss/grimoirelab-sortinghat and https://github.com/chaoss/grimoirelab-manuscripts probably need the same fix. Can you check them and submit a PR? Thanks!

**Comment by ria18405** [comment]
Sure, Im on it

**Comment by valeriocos** [comment]
Thanks @ria18405 !
