### ISSUE TITLE
[Slack] Update Slack API endoints and doc

### ISSUE THREAD

**Issue by animeshk08** [chaoss/grimoirelab-perceval#655]
The current slack end points used to fetch message data are:
*  [channel.history](https://api.slack.com/methods/channels.history)
*  [channel.info](https://api.slack.com/methods/channels.info)
*  [user.info](https://api.slack.com/methods/users.info)
Among the above endpoints `channel.info` and `channel.history` are deprecated.

These endpoints should be replaced accordingly:
* [channel.history](https://api.slack.com/methods/channels.history) -> [conversation.history](https://api.slack.com/methods/conversations.history)
* [channel.info](https://api.slack.com/methods/channels.info) -> [conversation.info](https://api.slack.com/methods/conversations.info)

Ref: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

Also, It is not evident from the current documentation what minimum scopes are required for the API token to run perceval for Slack. Since an error is thrown when scopes are not satisfied, I think this information should be added to the documentation.

**Comment by valeriocos** [comment]
Thank you @animeshk08 for opening this issue! There is also a change regarding the way tokens are issued: https://api.slack.com/legacy/custom-integrations/legacy-tokens

**Comment by animeshk08** [comment]
Thank you for the reference @valeriocos. To test the current implementation I had to create a slack app with the required scoped. This app was then installed by one of the user in a channel. After a successful installation, a `workspace token` was generated similar to `xoxp-1234.....`. This flow is similar to the one which telegram bot follows.

I believe Legacy tokens are user-specific and does not require the installation of slack apps.

I don't think much change is needed from our side only a bit of documentation update. The slack token documentation is a bit complicated so I would appreciate it if you could confirm if the above-mentioned flow is the best one for the creation of a token. I will start working on the endpoint change till then :)
Thanks!

**Comment by valeriocos** [comment]
Sorry for the late reply @animeshk08 

> I believe Legacy tokens are user-specific and does not require the installation of slack apps.

Yes, you are right!

> I don't think much change is needed from our side only a bit of documentation update.

I agree with you!

>  The slack token documentation is a bit complicated so I would appreciate it if you could confirm if the above-mentioned flow is the best one for the creation of a token. I will start working on the endpoint change till then :)
Thanks!

I think the flow is right, and similar to the one coded in the script at https://gist.github.com/valeriocos/de31324625a3fab32449cf5d43b24075. Please have a look and let me know if changes are needed, thanks!

**Comment by animeshk08** [comment]
Thank you for the reply @valeriocos should I provide a reference to this script in the documentation?

**Comment by valeriocos** [comment]
Yes, thank you @animeshk08 (sorry for the late replies, but I'm a bit busy these days)

**Comment by animeshk08** [comment]
No worries! I have updated the PR :)

**Comment by sduenas** [comment]
@animeshk08  I understand the structure of data didn't change, did it?
