### ISSUE TITLE
Rate limit info not set for gitlab backend

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#662]
It seems that the rate limit headers are not returned by the GitLab API anymore. Currently, this doesn't affect the working of the gitlab backend, however the logic to deal with rate limit data might be removed.

I wasn't able to find clear details about this removal, thus I opened an issue upstream: https://gitlab.com/gitlab-org/gitlab/-/issues/217312

**Comment by sduenas** [comment]
Interesting. I saw they were updating the server yesterday or the day before yesterday. Let's see if they reply to the ticket.

**Comment by sduenas** [comment]
This was fixed upstream.
