### ISSUE TITLE
[Feature Request] Add support for Trello

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-perceval#664]
Following the second community bonding meeting, I was thinking about a new feature, perceval support for Trello.

Trello is a web-based Kanban-style list-making application.
https://trello.com/

I would like to hear the opinions before we actually get started working.
@sduenas @valeriocos, WDYT?

**Comment by valeriocos** [comment]
Hi @vchrombie , thank you for triggering this discussion.

I believe that the idea is indeed interesting and this new backend could be a nice addition to Perceval. Said that, we should explore the Trello API and understand:
- which kind of info we can get from it (e.g., activities on single boards, users info)
- how to access the API (Oauth token or other credentials)
- which endpoints allow to retrieve the data in incremental way (e.g., after a given date/offset)

**Comment by vchrombie** [comment]
@valeriocos, I was almost commenting on it. :smiley: 

The main point here we should consider is what data we need to focus on.

Trello has different boards. Each Board has many lists (to-do, doing, done, etc.). Each list has different cards (we can assume as tasks). Whenever we do any change (like move a card from one list to another) the event is registered in the Activity.

So, we need to be clear about what we need to fetch from the API.
I have created a board to experiment with all of these things and with the API, [perceval-board](https://trello.com/invite/b/E60C2q8k/54f9719795bdbaa33b09290184ea29fa/perceval-board). You can try if you are interested.

API: https://developer.atlassian.com/cloud/trello/rest/

I would look into this, to refine the idea, in the coming days.

**Comment by valeriocos** [comment]
Thank you @vchrombie I'll have a look at the pointers you shared

**Comment by sduenas** [comment]
If someone wants to work on it, it would be great but I still think I prefer to have a less backends that work well and we use normally than many that nobody uses and are not well tested.

For this reason, it will be better if someone creates this backend, stores it in a separate repo (as we do with other backends like those strictly related to Mozilla tools) and we linked in the README.
If people use it and it doesn't have problems, we can add it to the owner of the backend wants that.

**Comment by vchrombie** [comment]
Closing this issue in favor of this https://github.com/chaoss/grimoirelab-perceval/issues/664#issuecomment-629854309.
