### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-perceval#665]
I was thinking if it would be a good idea to set up issue templates for the repository like 
- Feature-Request
- Bug Reporting
- Question/Doubt

Do you have any comments? @sduenas @valeriocos

**Comment by valeriocos** [comment]
The idea of using templates was suggested also on #640 (cc @animeshk08). There, it was also proposed to first clarify the management of the Perceval repos (and some bordeline backends), and then evaluate the use of templates. 

I report here my comment from that issue (ref 
https://github.com/chaoss/grimoirelab-perceval/pull/640#issuecomment-611659718).

> I'd love to use templates for issues and pull requests (not just related to new backends), this would probably simplify the contribution process and open the doors for automation. We can move this point to another issue (maybe better in the GrimoireLab main repo) and see what the community thinks about it...

**Comment by vchrombie** [comment]
Thanks, @valeriocos. Feel free to close the issue if you want.

**Comment by valeriocos** [comment]
You're welcome @vchrombie , let's leave it for a while to hear what other people think about this proposal.

**Comment by vchrombie** [comment]
Closing this issue as it is really complex to figure out a issue template for Perceval but I think it is a good to create on for https://github.com/chaoss/grimoirelab repository.
