### ISSUE TITLE
max-results option has no effect on jira query

### ISSUE THREAD

**Issue by gibello** [chaoss/grimoirelab-perceval#673]
Tried on project with many jira issues:
```
$ perceval jira https://jira.xwiki.org --project XWIKI --max-results 1
```
The command returns megabytes of JSON (just like no max-results specified ?), instead of just one record.

Note: using "--max-result" (without the S at "results") causes no error on the parameter name, but does not work better.

**Comment by valeriocos** [comment]
Hi @gibello ,

The `max-results` is used to set the number issues returned by every single query sent from Perceval to the Jira API.

I have tried the command you shared above and got the following:
```
$ perceval jira https://jira.xwiki.org --project XWIKI --max-results 1

[2020-06-05 11:23:37,069] - Sir Perceval is on his quest.
[2020-06-05 11:23:53,110] - Looking for issues at site 'https://jira.xwiki.org', in project 'XWIKI' and updated from '1970-01-01 00:00:00+00:00'
[2020-06-05 11:24:06,834] - Fetching 1/16218 items from https://jira.xwiki.org/rest/api/2/search
[2020-06-05 11:24:21,039] - Fetching 1/1 items from https://jira.xwiki.org/rest/api/2/issue/10318/comment
{
    "backend_name": "Jira",
    "backend_version": "0.14.0",
    "category": "issue",
    "classified_fields_filtered": null,
    "data": {...},
    "origin": "https://jira.xwiki.org",
    "perceval_version": "0.14.0",
    "search_fields": {
        "issue_key": "XWIKI-140",
        "item_id": "10318",
        "project_id": "10010",
        "project_key": "XWIKI",
        "project_name": "XWiki Platform"
    },
    "tag": "https://jira.xwiki.org",
    "timestamp": 1591349063.332433,
    "updated_on": 1124555836.0,
    "uuid": "0231a12ca12790f0f5f99eabc9d5a1eb0ff7d887"
}
[2020-06-05 11:24:23,769] - Fetching 2/16218 items from https://jira.xwiki.org/rest/api/2/search
..
[2020-06-05 11:24:23,769] - Fetching 2/16218 items from https://jira.xwiki.org/rest/api/2/search
...
[2020-06-05 11:33:43,921] - Fetching 3/16218 items from https://jira.xwiki.org/rest/api/2/search
..
```

As you can see from the log messages `Fetching x/16218`, only a document is returned by every query.

**Comment by valeriocos** [comment]
I close this issue @gibello , feel free to reopen it if needed.

**Comment by gibello** [comment]
Fine... but I don't find much doc about perceval backends - maybe I didn't manage to find it ?

Any way to filter issues (like obtaining only open issues, or sending some jql query to Jira ?) ? Is it "-tag" or any other (undocumented ?) param ?
Because on my case, there is too much data ("perceval jira https://jira.xwiki.org --project XWIKI" still running after 12 minutes... and almost 100 Mo download) so I have to filter primarily.

Thanks, and sorry for asking that if it's already in some doc I didn't find :)

**Comment by valeriocos** [comment]
> Fine... but I don't find much doc about perceval backends - maybe I didn't manage to find it ?

Some documentation is available at https://perceval.readthedocs.io/ (however it won't contain the latest changes: https://github.com/chaoss/grimoirelab-perceval/issues/625)

Another option is to execute the help command in Perceval, as follows:
```
$ perceval --help
$ perceval jira --help
```

> Any way to filter issues (like obtaining only open issues, or sending some jql query to Jira ?) ? Is it "-tag" or any other (undocumented ?) param ?

By default Perceval focuses on just collecting all data from a target repository. Filtering and drilling down into this data is done by other GrimoireLab components (ELK and Kibiter). 

You can either write a Python script that calls Perceval and retains only the data you want or modify the Jira backend logic (the Jql query is built at https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/jira.py#L375).

> Thanks, and sorry for asking that if it's already in some doc I didn't find :)

No worries, thank you for using Perceval :)
