### ISSUE TITLE
Add option to show the list of available backends dynamically

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval#690]
The command-line client should display the list of available backends. The current list is only shown with `perceval --help` but this list is static.

The idea is to have a flag (`-l / --list`, or similar) to display the list. So for instance, when the user runs the next command it will display the list shown on this example:

```
$ perceval --list

bugzilla
git
github
gitlab
[...]
jira
launchpad
mattermost
```
You can make use of the call to `find_backends` function. This function is called [here](https://github.com/chaoss/grimoirelab-perceval/blob/master/bin/perceval#L104)

**Comment by imnitishng** [comment]
I'm taking this up.
