### ISSUE TITLE
Improve log messages

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval#691]
Perceval is composed by several backends that allow to analyze heterogeneous datasources. In some of this backends, the log messages are not clear or they are poor. The goal of this task is to understand how backends work and include meaningful message logs that can help developer and users to understand the progress of the backend.

This is a log running task, so feel free to chose a backend  and send PRs improving those log messages. Different people can work on this at the same time. This is the full list of backends currently supported in the core of Perceval:

- [ ] askbot.py
- [ ] bugzilla.py
- [ ] bugzillarest.py
- [ ] confluence.py
- [ ] discourse.py
- [ ] dockerhub.py
- [ ] gerrit.py
- [ ] github.py
- [ ] githubql.py
- [ ] gitlab.py
- [ ] git.py
- [ ] gitter.py
- [ ] googlehits.py
- [ ] groupsio.py
- [ ] hyperkitty.py
- [ ] jenkins.py
- [ ] jira.py
- [ ] launchpad.py
- [ ] mattermost.py
- [ ] mbox.py
- [ ] mediawiki.py
- [ ] meetup.py
- [ ] nntp.py
- [ ] pagure.py
- [ ] phabricator.py
- [ ] pipermail.py
- [ ] redmine.py
- [ ] rocketchat.py
- [ ] rss.py
- [ ] slack.py
- [ ] stackexchange.py
- [ ] supybot.py
- [ ] telegram.py
- [ ] twitter.py

**Comment by nworb95** [comment]
I am happy to help work on this!

**Comment by nworb95** [comment]
(Just going to go through the tutorial first)

**Comment by Rashmi-K-A** [comment]
@sduenas  I would love to work on this, but can you elaborate on the 'log messages are not clear or they are poor' part, and perhaps provide an example? I went through these files but I am still trying to put a finger on what we are defining as 'good log messages'

**Comment by jaskiratsingh2000** [comment]
@sduenas I am super interested to work on this issue. I just need a clarified idea that you are looking forward to this. Can you please let me know the whole idea that you want me to implement? What do you mean by a "good" or "poor" error message here?

**Comment by jaskiratsingh2000** [comment]
Hey @sduenas Can you please let me know on this. I am still looking forward to hearing from you.

**Comment by codewith-arijit** [comment]
Is this issue still open? Can I be assigned to work on it?

**Comment by sduenas** [comment]
Closing this task because it's been a while an nobody has been working on it or have reported problems. Feel free to open it again.
