### ISSUE TITLE
Version mismatch between PyPi and source code?

### ISSUE THREAD

**Issue by kerrerain** [chaoss/grimoirelab-perceval#704]
Hello,

I'm asking out of curiosity: the last release of perceval published on PyPi is [0.12.24](https://pypi.org/project/perceval/), but it seems that the last versions mentionned in the source code are 0.17.x. Are the release published elsewhere, or is the team currently preparing a future release?

Regards,

kerrerain.

**Comment by sduenas** [comment]
Hi, yes. I'm trying to fix that problem this afternoon. I also need to update all the packages for the whole stack. I'll keep you posted.

**Comment by sduenas** [comment]
I've uploaded updated versions of the packages to pypi. Feel free to open this ticket again if you find any problem.

**Comment by sduenas** [comment]
Great news! Thanks and sorry because it take so much to upload a new version of the packages.
