### ISSUE TITLE
Add backend support for osf.io

### ISSUE THREAD

**Issue by Nolski** [chaoss/grimoirelab-perceval#719]
# Overview

[Open@RIT](https://www.rit.edu/research/open) uses perceval (along with the rest of the grimoire lab stack) to collect metrics across a variety of academic open research projects. As a center of excellence within RIT, we hope to expand our metrics collected to go beyond simply Free and open source software to other sorts of open programs such as https://osf.io which is an increasingly popular platform for hosting research materials. 

## Further details

As a first step of adding this support, we want to be able to collect relevant data on users open projects on osf.io through their [API](https://developer.osf.io/#tag/Filtering).

@suhascv is interested in contributing this functionality to perceval and has already started investigating how to do so.

## Open questions

This will be our first time contributing a backend, it would be great to know about any things we should take into account such as

- Specific required formats of the data we collect
- Relevant documentation or PRs that might be helpful
- Guidelines that aren't otherwise stated in CONTRIBUTING.md and perhaps most importantly...
- If CHAOSS is interested in accepting this new functionality upstream

Happy hacking!

**Comment by vchrombie** [comment]
Hi @Nolski @suhascv, thanks for your interest in GrimoireLab.
I think @sduenas has covered almost everything that is needed.

I just wanted to add one more thing. If you are looking to contribute to GrimoireLab (as a whole), you can follow the [developer installation guide](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md). This would make things much easier for you.

Let us know if you need any more help. :)

**Comment by Nolski** [comment]
Hi @sduenas and @vchrombie this all sounds good! We're more than happy to maintain the osf integration as its own repository. Perhaps we can leave this issue open as a reminder to add to the documentation here so perceval users can know of our 3rd party backend?

**Comment by suhascv** [comment]
Hi @vchrombie and @sduenas ,
Just wanted to update on our work, we have started developing  [osf perceval backend](https://gitlab.com/open-rit/perceval-osf), we have achieved basic ```--category``` fetch so far. 
Your suggestions are welcome .
[https://gitlab.com/open-rit/perceval-osf)](https://gitlab.com/open-rit/perceval-osf)

**Comment by vchrombie** [comment]
Hi all, thanks to everyone for working on perceval-osf. I have just merged https://github.com/chaoss/grimoirelab-perceval/pull/750 and the addition of osf backend looks great to the list.

Do you think we can close the issue now?

Please feel free to open any issues in case of any other doubt.

**Comment by sduenas** [comment]
@vchrombie yes, please. I think we can close this.

**Comment by vchrombie** [comment]
Thank you everyone for being a part of the discussion. :slightly_smiling_face: 
Please feel free to open a new issue in case of any doubts in the future.
