### ISSUE TITLE
No module named "setuptools"

### ISSUE THREAD

**Issue by suhascv** [chaoss/grimoirelab-perceval#720]
# Error while installing requirements from [toolkit](https://github.com/chaoss/grimoirelab-toolkit)
```pip3 install -r requirements.txt``` 

![Screenshot from 2021-02-24 10-00-13](https://user-images.githubusercontent.com/43292181/109019745-467a1300-7687-11eb-913d-a8140b685697.png)

I get the same error even after
```
pip3 install setuptools
Requirement already satisfied: setuptools in
```

@Nolski

**Comment by suhascv** [comment]
The following changes in [pyproject.toml](https://github.com/chaoss/grimoirelab-perceval/blob/master/pyproject.toml) solved the issue
```p3
[build-system]
requires = ["poetry-core>=1.0.0",
            "setuptools>=30.3.0,<50"
]
```

**Comment by sduenas** [comment]
Thanks! Would you mind to create a PR to fix it?

**Comment by suhascv** [comment]
sure 
need to make the above changes to both perceval repo and toolkit repo
[perceval PR](https://github.com/chaoss/grimoirelab-perceval/pull/721)
[toolkit PR](https://github.com/chaoss/grimoirelab-toolkit/pull/34)

**Comment by vchrombie** [comment]
Hi @suhascv @Nolski, thanks for your interest in GrimoireLab. Sorry for popping in late.

I think we have faced this issue earlier and we found a workaround for it. We are using the same workaround in the [CI workflow](https://github.com/chaoss/grimoirelab-perceval/blob/master/.github/workflows/ci.yml) too.

It is always advised to use a virtual environment, in case if you aren't using one.
```
mkdir venv && python -m venv venv && source venv/bin/activate
```

Installing perceval from source code
```
git clone https://github.com/chaoss/grimoirelab-perceval.git
cd grimoirelab-perceval
pip install --upgrade pip==18.1 setuptools==49.6 wheel
pip install -r requirements.txt
pip install .
perceval --list
```
@suhascv, can you try this and let us know if this solves the issue?

If we still want to proceed with adding setuptools to the requirements and poetry configuration, we need to make sure it doesn't affect any other tools, and also maybe we need to update the github actions workflows too. I can help with testing that.
@sduenas, do you have any thoughts?

**Comment by suhascv** [comment]
@vchrombie thanks for your response, I followed the above procedure using virtual environment, I still got the same error. It seems like [this](https://github.com/pypa/setuptools/issues/2353#issue-688935202) is the issue here.

**Comment by vchrombie** [comment]
Hi @suhascv 

> @vchrombie thanks for your response, I followed the above procedure using virtual environment, I still got the same error. It seems like [this](https://github.com/pypa/setuptools/issues/2353#issue-688935202) is the issue here.

Strange, I have tested the steps just now and it works really fine for me.

> ```
> git clone https://github.com/chaoss/grimoirelab-perceval.git
> cd grimoirelab-perceval
> pip install --upgrade pip==18.1 setuptools==49.6 wheel
> pip install -r requirements.txt
> pip install .
> perceval --list
> ```

Do you mind sharing any error log you have?

Just a small trivia, you can try `python setup.py install` instead of `pip install .`.

Also, are you interested to try the [developer installation of grimoirelab](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#cloning-the-repositories-)? I understand you are working with only perceval right now, but this can very much helpful. I can help you with the setup if needed.

**Comment by vchrombie** [comment]
@suhascv do you have doubts or update about the installation?
Let me know if you need help.

**Comment by vchrombie** [comment]
@suhascv can we close this issue for now?

We, right now, need to downgrade the version of the setuptools as a workaround but I am hoping this error would be resolved in the coming version of setuptools.

If it didn't, I will try to implement the changes which you have proposed. But, I need to evaluate if this is needed for all the grimoirelab tools.

**Comment by suhascv** [comment]
@vchrombie you can close this issue.

**Comment by sduenas** [comment]
I've been facing the same problems @suhascv had. I think we should add it to avoid the problem while the issue with setuptools is fixed.

**Comment by vchrombie** [comment]
> I've been facing the same problems @suhascv had. I think we should add it to avoid the problem while the issue with setuptools is fixed.

Okay @sduenas, I will follow up on this PR https://github.com/chaoss/grimoirelab-perceval/pull/721 and check if other grimoirelab components need this change.

**Comment by rohanreddych** [comment]
Hello, I followed suhascv's tip and put `requires = ["poetry-core>=1.0.0","setuptools>=30.3.0,<50"]` in `pyproject.toml` but it still gave an error. 
```
Running setup.py develop for grimoirelab-toolkit
    ERROR: Command errored out with exit status 1:
     command: /mnt/c/Users/rohan/workspace/chaoss/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /mnt/c/Users/rohan/workspace/chaoss/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
I created a new virtualenv and tried again, but same error. Any fix for this error?

**Comment by vchrombie** [comment]
Hi @rohanreddych, thanks for your interest in GrimoireLab.

> Hello, I followed suhascv's tip and put `requires = ["poetry-core>=1.0.0","setuptools>=30.3.0,<50"]` in `pyproject.toml` but it still gave an error.

Okay, I haven't really tried that solution but it should solve the problem.
Have you installed setuptools after adding them to the `pyproject.toml`. You can install it using pip. Ideally this should be added to `requirements.txt` file.
```
$ pip install -r setuptools>=30.3.0,<50
```

I will check this soon and provide the required PR.

You can also try the steps given in this [chaoss/grimoirelab-perceval#720 (comment)](https://github.com/chaoss/grimoirelab-perceval/issues/720#issuecomment-785699601). This is a workaround which we are currently using now.

**Comment by suhascv** [comment]
> Hello, I followed suhascv's tip and put `requires = ["poetry-core>=1.0.0","setuptools>=30.3.0,<50"]` in `pyproject.toml` but it still gave an error.
> 
> ```
> Running setup.py develop for grimoirelab-toolkit
>     ERROR: Command errored out with exit status 1:
>      command: /mnt/c/Users/rohan/workspace/chaoss/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
>          cwd: /mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/
>     Complete output (3 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>     ModuleNotFoundError: No module named 'setuptools'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /mnt/c/Users/rohan/workspace/chaoss/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/mnt/c/Users/rohan/workspace/chaoss/venv/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
> ```
> 
> I created a new virtualenv and tried again, but same error. Any fix for this error?

@rohanreddych I think you need to update ```pyproject.toml``` on two repos 

1. [perceval](https://github.com/chaoss/grimoirelab-perceval)
2. [toolkit](https://github.com/chaoss/grimoirelab-toolkitl) 

I forked both these repos and updated ```pyproejct.toml```, it worked for me.
