### ISSUE TITLE
What should I use for 'hostname' attribute to extract data from Gerrit?

### ISSUE THREAD

**Issue by isikozsoy** [chaoss/grimoirelab-perceval#724]
Hi everyone, I want to extract code reviews from a public gerrit project. I tried to write "gerrit.wikimedia.org/WikiApiary" as hostname however I got following error ssh: Could not resolve hostname gerrit.wikimedia.org/wikiapiary: Name or service not known
Can anyone help me, where should I look for hostname attribute of Gerrit? Thanks for your time.

**Comment by sduenas** [comment]
You can't analyze just one part of the gerrit repository. You need to get all the review from the whole repo. Therefore, the hostname will be `gerrit.wikimedia.org`.

 To do that, you also need to have an account in wikimedia. See the documentation about how to configure it: https://github.com/chaoss/grimoirelab-perceval#gerrit

**Comment by isikozsoy** [comment]
Thanks a lot!
