### ISSUE TITLE
Gitlab platform returns different results than perceval

### ISSUE THREAD

**Issue by kayleachampion** [chaoss/grimoirelab-perceval#768]
Hi, I am working my way through the perceval tutorial and there is some inconsistency with the commit count from perceval versus what I see if I go to the gitlab repository site directly. I don't have this issue with github repositories, however.

Steps to reproduce:

Visit https://gitlab.gnome.org/GNOME/gnome-power-manager 
--> commit count is **4,452**

Use script perceval_git_counter.py from https://perceval.readthedocs.io/en/latest/perceval/git.html

python3 perceval_git_counter.py https://gitlab.gnome.org/GNOME/gnome-power-manager /path/to/my/cache/gnome-power-manager

---> commit count is **5,274**

By contrast, with the same script pointed at github, I get the same number from the script and from the web UI, e.g. 
python3 perceval_git_counter.py https://github.com/bluez/bluez.git /path/to/my/cache/bluez

--> commit count is the same on the website and from the script: 26,259

Thanks in advance for your help!

**Comment by sduenas** [comment]
GitLab shows the number of commits in the master branch. With perceval you are getting the commits that are in all the branches available in the repository.

Hope this answers your question.
