### ISSUE TITLE
[Git] Won't delete the old tags when calling `__fetch_newest_commits_from_repo`

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-perceval#782]
https://github.com/chaoss/grimoirelab-perceval/blob/d4d86869ebe5a2bb9ba5fe3f150fdce7294d98e6/perceval/backends/core/git.py#L1162-L1168

It seems that it will only delete those old references (`refs/heads/*`) and will not delete these old references (`refs/tags/*`).

If the server deletes the tag, should the tag of the local repo be deleted?

**Comment by vchrombie** [comment]
Since #845 is merged, I guess we can close this.

**Comment by sduenas** [comment]
Good catch!. Closing it.
