### ISSUE TITLE
Peceval: configuration option for self-signed SSL certificate

### ISSUE THREAD

**Issue by zemunk** [chaoss/grimoirelab-perceval#826]
**Type:** Feature Request

**Issue description:**
I am connecting to a GitHub Enterprise playground server as data source to fetch repositories. These playground servers are often not secured with a certificate from an official certification authority, but a self-signed one. This does not go well with git per default.

It is possible to configure git on the Perceval container to work with this certificate, but every time after the container is shut down, this configuration has to be re-done.

**Request:**
If it is possible to do, it would be a major help to have a persistent configuration option to register this self-signed certificate, which is then picked up by the Perceval container on startup.

Error message example:
![image](https://github.com/chaoss/grimoirelab-perceval/assets/23052922/5b1826e5-89b3-4cff-8097-b36ae906dbce)

**Comment by sduenas** [comment]
Why don't you use a volume to persist the data and the certificates?

**Comment by sduenas** [comment]
For docker you should use persistent volumes so you can reuse the certificates.

**Comment by zemunk** [comment]
Thank you for your suggestion, we will try it like this.
