### ISSUE TITLE
Bugzilla and datetime_to_utc

### ISSUE THREAD

**Issue by maelick** [chaoss/grimoirelab-perceval#91]
In the REST backend for Bugzilla, the from_date parameter is converted to UTC while it isn't in the CGI version. Is there any particular reason for that?

(See https://github.com/grimoirelab/perceval/blob/4ebe6f596386d265e86d76dce1a442521e7f7caf/perceval/backends/bugzillarest.py#L373
and https://github.com/grimoirelab/perceval/blob/81c4eb56f5bacfb5f46a6e18ccd736f70343b96f/perceval/backends/bugzilla.py#L573)

**Comment by sduenas** [comment]
Yes, there is. When using the CGI to fetch bugs, Bugzilla server does not support timezones. The server expects that every given date is on its same timezone (the timezone of the server). For instance:

* This one will raise an error:
```
https://bugzilla.redhat.com/buglist.cgi?chfieldfrom="2016-11-08 10:40:00+0200"
```
* These two return the same results event when one of them is in UTC:
```
https://bugzilla.redhat.com/buglist.cgi?chfieldfrom="2016-11-08 10:40:00"
https://bugzilla.redhat.com/buglist.cgi?chfieldfrom="2016-11-08 10:40:00Z"
```

There is a bug open regarding to this problem: https://bugzilla.mozilla.org/show_bug.cgi?id=822629


In the other hand, the Bugzilla's REST API supports timezones in UTC. See: http://bugzilla.readthedocs.io/en/latest/api/core/v1/bugzilla.html

**Comment by maelick** [comment]
This actually caused the Bugzilla backend to loop infinitely when trying to fetch bugs from repositories hosted in America, such as the one from Mozilla. For example yesterday running
`perceval -g bugzilla "https://bugzilla.mozilla.org" -o out --from-date 2016-11-01`
gave the following kind of output https://gist.github.com/maelick/47ad9ef52f4f53563475c11dd2301ee1

I also tried (before) to use the REST API but there is another problem when trying to get all bugs from Mozilla's repository. After a few hours Perceval crashes because of an error 500. I've modified the BugzillaREST backend to add a few options to filter bugs, and (hopefully) be able to get all the bugs from large repositories such as Mozilla's. I'll soon add a PR with the patch.

**Comment by sduenas** [comment]
Yes, this is a known bug and that's the reason why we decided to add `bugzillarest` backend. The server works that way (it's a bug, IMHO) and I didn't find a way to make `bugzilla` backend work.

If `bugzillarest` fails, you can resume the work taking the last item it generated, convert the `updated_on` value (it's in Unix time) to a valid datetime (i.e http://www.epochconverter.com/), and using that value as `--from-date` argument. This will resume the work.
